#!/usr/bin/env python3
"""生成模块2的全部Jupyter notebook — 深度学习入门"""
import json, os

DIR = os.path.dirname(os.path.abspath(__file__))

def nb(cells):
    return {"nbformat":4,"nbformat_minor":5,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"cells":cells}

def md(s):
    return {"cell_type":"markdown","metadata":{},"source":s if isinstance(s,list) else [s]}

def code(s):
    return {"cell_type":"code","metadata":{},"source":s if isinstance(s,list) else [s],"execution_count":None,"outputs":[]}

def write(name, cells):
    with open(os.path.join(DIR, name),'w',encoding='utf-8') as f:
        json.dump(nb(cells), f, ensure_ascii=False, indent=1)
    print(f"Written: {name}")

# ============================================================
# 01-linear-regression.ipynb
# ============================================================
nb1 = [
md(["# 从感知机到神经网络\n","\n","## 学习目标\n","\n","- 理解\"学习\"就是\"调参数\"的过程\n","- 用纯Python实现线性回归，观察梯度下降\n","- 用PyTorch重写同样的模型，理解框架帮我们做了什么\n","- 理解损失函数、梯度、学习率的概念\n","\n","## 本节核心思想\n","\n","> **深度学习 = 用数据自动调整参数**。仅此而已。\n","> 所谓的\"学习\"，就是不断微调参数，让预测结果越来越接近真实值。\n"]),

md(["## 1. 线性回归：最简单的\"学习\"\n","\n","假设我们有一些数据点，想找到一条直线来拟合它们。\n","\n","这就是最简单的\"学习\"：找到最好的参数(w, b)，让 $y = wx + b$ 尽可能接近真实数据。"]),

code(["import numpy as np\n","import matplotlib.pyplot as plt\n","np.random.seed(42)\n","plt.rcParams['font.size'] = 12\n","plt.rcParams['figure.figsize'] = (10, 4)"]),

md(["### 1.1 生成数据\n","\n","我们生成一组\"频率 → 振幅衰减\"的数据：频率越高，振幅衰减越大。\n","这在CI研究中很常见——高频通道的增益通常低于低频通道。"]),

code(["# 生成模拟数据：频率 → 振幅衰减\n","freq = np.random.uniform(100, 8000, 50)  # 频率 100-8000 Hz\n","true_w = -0.00005  # 真实斜率：频率越高，振幅越小\n","true_b = 0.9       # 真实截距\n","amplitude = true_w * freq + true_b + np.random.normal(0, 0.05, 50)  # 加噪声\n","\n","plt.figure(figsize=(10, 4))\n","plt.scatter(freq, amplitude, alpha=0.6)\n","plt.xlabel('Frequency (Hz)')\n","plt.ylabel('Amplitude')\n","plt.title('Frequency vs Amplitude Attenuation')\n","plt.grid(True, alpha=0.3)\n","plt.show()"]),

md(["### 1.2 纯Python实现梯度下降\n","\n","现在我们要\"学习\"到 w 和 b 的值。\n","\n","**核心流程**：\n","1. 随机初始化 w 和 b\n","2. 用当前的 w 和 b 计算预测值\n","3. 计算预测值和真实值的差距（损失）\n","4. 计算\"往哪个方向调参数能让损失变小\"（梯度）\n","5. 调整参数（梯度下降）\n","6. 重复 2-5"]),

code(["# ====== 纯Python实现梯度下降 ======\n","\n","# 初始化参数（随机值）\n","w = 0.0\n","b = 0.0\n","learning_rate = 0.00000001  # 学习率\n","n_epochs = 100              # 训练轮数\n","n_samples = len(freq)\n","\n","# 记录训练过程\n","losses = []\n","ws = []\n","bs = []\n","\n","for epoch in range(n_epochs):\n","    # 前向传播：计算预测值\n","    predictions = w * freq + b\n","    \n","    # 计算损失（均方误差）\n","    loss = np.mean((predictions - amplitude) ** 2)\n","    losses.append(loss)\n","    \n","    # 计算梯度（损失对参数的偏导数）\n","    dw = (2 / n_samples) * np.sum((predictions - amplitude) * freq)\n","    db = (2 / n_samples) * np.sum(predictions - amplitude)\n","    \n","    # 更新参数\n","    w = w - learning_rate * dw\n","    b = b - learning_rate * db\n","    \n","    ws.append(w)\n","    bs.append(b)\n","\n","print(f'训练结果: w = {w:.8f}, b = {b:.4f}')\n","print(f'真实值:   w = {true_w:.8f}, b = {true_b:.4f}')\n","print(f'最终损失: {losses[-1]:.6f}')"]),

code(["# 可视化训练过程\n","fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n","\n","# 损失曲线\n","axes[0].plot(losses)\n","axes[0].set_xlabel('Epoch')\n","axes[0].set_ylabel('Loss (MSE)')\n","axes[0].set_title('Training Loss')\n","axes[0].grid(True, alpha=0.3)\n","\n","# 参数w的变化\n","axes[1].plot(ws, label='Learned w')\n","axes[1].axhline(y=true_w, color='r', linestyle='--', label='True w')\n","axes[1].set_xlabel('Epoch')\n","axes[1].set_ylabel('w')\n","axes[1].set_title('Parameter w')\n","axes[1].legend()\n","axes[1].grid(True, alpha=0.3)\n","\n","# 拟合结果\n","x_line = np.linspace(100, 8000, 100)\n","axes[2].scatter(freq, amplitude, alpha=0.4, label='Data')\n","axes[2].plot(x_line, w * x_line + b, 'r-', linewidth=2, label='Fitted line')\n","axes[2].plot(x_line, true_w * x_line + true_b, 'g--', linewidth=2, label='True line')\n","axes[2].set_xlabel('Frequency (Hz)')\n","axes[2].set_ylabel('Amplitude')\n","axes[2].set_title('Fitted Result')\n","axes[2].legend()\n","axes[2].grid(True, alpha=0.3)\n","\n","plt.tight_layout()\n","plt.show()"]),

md(["### 1.3 关键概念\n","\n","**损失函数 (Loss Function)**：衡量\"预测值和真实值差多远\"。上面用的是均方误差(MSE)。\n","\n","**梯度 (Gradient)**：告诉参数\"该变大还是变小\"。梯度就是损失函数对参数的偏导数。\n","\n","**学习率 (Learning Rate)**：每次调参数的步长。太大→震荡，太小→慢。\n","\n","**梯度下降 (Gradient Descent)**：沿着梯度的反方向调整参数。就像下山——沿着最陡的方向往下走。"]),

md(["### 练习1：调整学习率\n","\n","修改上面的代码，尝试不同的学习率，观察训练过程：\n","- `learning_rate = 0.0000001`（太小）\n","- `learning_rate = 0.00001`（合适）\n","- `learning_rate = 0.001`（太大）\n","\n","**问题**：学习率太大时，损失曲线会怎样？为什么？"]),

md(["## 2. 用PyTorch重写——框架帮我们做了什么？\n","\n","刚才我们手动实现了梯度计算和参数更新。PyTorch帮我们自动做了这两件事：\n","1. **自动微分**：不需要手算梯度\n","2. **优化器**：不需要手写参数更新规则"]),

code(["import torch\n","import torch.nn as nn\n","import torch.optim as optim\n","\n","# 准备数据（转为PyTorch张量）\n","freq_tensor = torch.FloatTensor(freq).unsqueeze(1)   # shape: [50, 1]\n","amp_tensor = torch.FloatTensor(amplitude).unsqueeze(1) # shape: [50, 1]\n","\n","# 定义模型\n","model = nn.Linear(1, 1)  # 输入1维，输出1维\n","\n","# 定义损失函数和优化器\n","criterion = nn.MSELoss()\n","optimizer = optim.SGD(model.parameters(), lr=1e-7)\n","\n","# 训练\n","losses_torch = []\n","for epoch in range(100):\n","    # 前向传播\n","    predictions = model(freq_tensor)\n","    \n","    # 计算损失\n","    loss = criterion(predictions, amp_tensor)\n","    losses_torch.append(loss.item())\n","    \n","    # 反向传播（自动计算梯度！）\n","    optimizer.zero_grad()  # 清零梯度\n","    loss.backward()        # 计算梯度\n","    optimizer.step()       # 更新参数\n","\n","# 查看结果\n","w_learned = model.weight.item()\n","b_learned = model.bias.item()\n","print(f'PyTorch结果: w = {w_learned:.8f}, b = {b_learned:.4f}')\n","print(f'纯Python结果: w = {w:.8f}, b = {b:.4f}')\n","print(f'真实值:       w = {true_w:.8f}, b = {true_b:.4f}')"]),

md(["### 对比\n","\n","| 方面 | 纯Python | PyTorch |\n","|------|---------|----------|\n","| 梯度计算 | 手动推导偏导数 | `loss.backward()` 自动计算 |\n","| 参数更新 | 手动写 `w = w - lr * dw` | `optimizer.step()` 自动更新 |\n","| 模型定义 | 直接用变量 | `nn.Linear` 封装 |\n","| 代码量 | 多 | 少 |\n","\n","**PyTorch帮我们省略了最繁琐的部分（梯度计算和参数更新），让我们专注于模型设计。**"]),

md(["## 3. 张量(Tensor)——PyTorch的核心数据结构\n","\n","张量就是\"多维数组\"，和NumPy的ndarray很像，但可以在GPU上运算。"]),

code(["# 张量基础\n","import torch\n","\n","# 创建张量\n","a = torch.tensor([1.0, 2.0, 3.0])       # 从列表创建\n","b = torch.zeros(3)                       # 全0\n","c = torch.ones(2, 3)                     # 全1，形状2x3\n","d = torch.randn(2, 3)                    # 随机数，形状2x3\n","\n","print(f'a = {a}')\n","print(f'b = {b}')\n","print(f'c = {c}')\n","print(f'd = {d}')\n","print(f'd.shape = {d.shape}')  # 形状"]),

code(["# 张量运算\n","x = torch.randn(3, 4)\n","y = torch.randn(3, 4)\n","\n","print('逐元素运算:')\n","print(f'x + y 的形状: {(x + y).shape}')\n","print(f'x * y 的形状: {(x * y).shape}')  # 逐元素乘法\n","\n","print('\\n矩阵运算:')\n","z = torch.randn(4, 2)\n","print(f'x @ z 的形状: {(x @ z).shape}')  # 矩阵乘法\n","\n","print('\\n与NumPy互转:')\n","np_array = x.numpy()           # Tensor → NumPy\n","tensor_from_np = torch.from_numpy(np_array)  # NumPy → Tensor\n","print(f'互转后数据一致: {np.allclose(x.numpy(), tensor_from_np.numpy())}')"]),

code(["# GPU加速\n","if torch.cuda.is_available():\n","    x_gpu = x.to('cuda')\n","    print(f'张量在设备: {x_gpu.device}')\n","    print(f'GPU矩阵乘法...')\n","    \n","    # 大矩阵乘法对比\n","    import time\n","    size = 2000\n","    \n","    # CPU\n","    a_cpu = torch.randn(size, size)\n","    b_cpu = torch.randn(size, size)\n","    start = time.time()\n","    c_cpu = a_cpu @ b_cpu\n","    cpu_time = time.time() - start\n","    \n","    # GPU\n","    a_gpu = a_cpu.to('cuda')\n","    b_gpu = b_cpu.to('cuda')\n","    start = time.time()\n","    c_gpu = a_gpu @ b_gpu\n","    torch.cuda.synchronize()\n","    gpu_time = time.time() - start\n","    \n","    print(f'CPU: {cpu_time*1000:.1f} ms, GPU: {gpu_time*1000:.1f} ms')\n","    print(f'加速比: {cpu_time/gpu_time:.1f}x')\n","else:\n","    print('GPU不可用，跳过GPU演示')"]),

md(["## 4. 自动微分——PyTorch最强大的功能\n","\n","PyTorch的 `autograd` 系统可以自动计算梯度，你不需要手算任何偏导数。"]),

code(["# 自动微分示例\n","x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)\n","\n","# 做一些运算\n","y = x ** 2       # y = x²\n","z = y.sum()      # z = Σx²\n","\n","# 反向传播——自动计算梯度\n","z.backward()\n","\n","# 查看梯度：dz/dx = 2x\n","print(f'x = {x}')\n","print(f'x的梯度 (应为2x) = {x.grad}')\n","print(f'验证: 2 * x = {2 * x}')"]),

md(["### 自动微分的意义\n","\n","上面的例子中，$z = \\sum x_i^2$，手动计算 $\\frac{\\partial z}{\\partial x_i} = 2x_i$。\n","\n","PyTorch帮我们自动完成了这个计算。对于简单的函数，手算不难；\n","但对于深度神经网络（几十层，上百万参数），手动计算梯度几乎不可能——这就是自动微分的价值。\n","\n","**记住**：`loss.backward()` = 自动计算所有参数的梯度；`optimizer.step()` = 用梯度更新参数。你只需要做这两步。"]),

md(["## 本节要点\n","\n","1. **学习 = 调参数**：找到最好的参数让预测接近真实值\n","2. **梯度下降**：沿梯度的反方向调整参数，就像下山\n","3. **损失函数**：衡量预测和真实的差距\n","4. **学习率**：步长，太大→震荡，太小→慢\n","5. **PyTorch做了什么**：自动微分(gradient) + 优化器(optimizer)，让我们专注模型设计\n","6. **张量**：PyTorch的核心数据结构，和NumPy数组类似但支持GPU\n"]),

md(["---\n","下一节：[02-mlp-pytorch.ipynb](02-mlp-pytorch.ipynb) — MLP与反向传播"]),
]

# ============================================================
# 02-mlp-pytorch.ipynb
# ============================================================
nb2 = [
md(["# MLP与反向传播\n","\n","## 学习目标\n","\n","- 理解为什么需要激活函数（非线性）\n","- 理解多层感知机(MLP)的结构\n","- 理解反向传播的直觉\n","- 能用PyTorch搭建MLP并训练\n","- 完成第一个真正的训练任务：正弦波分类\n"]),

md(["## 1. 为什么需要激活函数？\n","\n","如果没有激活函数，无论多少层线性变换叠加，结果仍然是线性的——跟一层没有区别。\n","\n","**物理直觉**：人对声音响度的感知不是线性的，而是对数的。这就是一种非线性变换！\n","CI的频率-电极映射也不是线性的——低频区域分配更多电极。这又是一种非线性。"]),

code(["import numpy as np\n","import matplotlib.pyplot as plt\n","import torch\n","import torch.nn as nn\n","\n","plt.rcParams['font.size'] = 12\n","plt.rcParams['figure.figsize'] = (10, 4)\n","\n","# 常见激活函数\n","x = np.linspace(-5, 5, 200)\n","\n","fig, axes = plt.subplots(1, 4, figsize=(16, 3))\n","\n","# ReLU\n","axes[0].plot(x, np.maximum(0, x))\n","axes[0].set_title('ReLU')\n","axes[0].axhline(y=0, color='k', linewidth=0.5)\n","axes[0].axvline(x=0, color='k', linewidth=0.5)\n","axes[0].grid(True, alpha=0.3)\n","\n","# Sigmoid\n","axes[1].plot(x, 1 / (1 + np.exp(-x)))\n","axes[1].set_title('Sigmoid')\n","axes[1].grid(True, alpha=0.3)\n","\n","# Tanh\n","axes[2].plot(x, np.tanh(x))\n","axes[2].set_title('Tanh')\n","axes[2].grid(True, alpha=0.3)\n","\n","# LeakyReLU\n","axes[3].plot(x, np.where(x > 0, x, 0.01 * x))\n","axes[3].set_title('LeakyReLU')\n","axes[3].grid(True, alpha=0.3)\n","\n","plt.tight_layout()\n","plt.show()"]),

md(["### ReLU ≈ 半波整流\n","\n","对学过信号处理的人来说，ReLU其实就是**半波整流器**！\n","\n","$$\\text{ReLU}(x) = \\max(0, x)$$\n","\n","信号处理中的半波整流：把负半周全部截掉，只保留正半周。ReLU做的完全一样的事。\n","这就是深度学习和信号处理的连接——很多概念你其实已经知道了，只是名字不同。"]),

md(["## 2. MLP的结构\n","\n","多层感知机(MLP) = 多层线性变换 + 激活函数\n","\n","```\n","输入 → 线性层 → 激活 → 线性层 → 激活 → ... → 输出\n","```\n","\n","关键点：\n","- 每一层都是独立的线性变换+非线性激活\n","- 层数越多，模型能表达的函数越复杂（表达能力越强）\n","- 但层太多也可能过拟合"]),

code(["# 用PyTorch定义MLP\n","import torch.nn as nn\n","\n","class SimpleMLP(nn.Module):\n","    def __init__(self, input_dim, hidden_dim, output_dim):\n","        super().__init__()\n","        self.layers = nn.Sequential(\n","            nn.Linear(input_dim, hidden_dim),   # 输入层 → 隐藏层\n","            nn.ReLU(),                          # 激活函数\n","            nn.Linear(hidden_dim, hidden_dim),   # 隐藏层 → 隐藏层\n","            nn.ReLU(),                          # 激活函数\n","            nn.Linear(hidden_dim, output_dim),   # 隐藏层 → 输出层\n","        )\n","    \n","    def forward(self, x):\n","        return self.layers(x)\n","\n","# 创建模型\n","model = SimpleMLP(input_dim=160, hidden_dim=64, output_dim=2)\n","print(model)\n","print(f'\\n参数总数: {sum(p.numel() for p in model.parameters()):,}')"]),

md(["## 3. 反向传播的直觉\n","\n","反向传播(backpropagation)就是**自动计算梯度**的具体算法。\n","\n","直觉理解：\n","1. 前向传播：数据从输入层流向输出层，得到预测值\n","2. 计算损失：预测值和真实值的差距\n","3. 反向传播：\"误差信号\"从输出层反向流回输入层\n","4. 每个参数问自己：\"我该变大还是变小才能减少误差？\"\n","\n","你不需要知道链式法则的数学细节——PyTorch的 `autograd` 帮你做了。\n","你只需要理解：**`loss.backward()` 会计算所有参数的梯度，`optimizer.step()` 会用这些梯度更新参数。**"]),

code(["# 反向传播可视化\n","model = SimpleMLP(input_dim=160, hidden_dim=64, output_dim=2)\n","x = torch.randn(4, 160)  # batch_size=4, input_dim=160\n","y = torch.randint(0, 2, (4,))  # 4个标签\n","\n","# 前向传播\n","output = model(x)\n","loss = nn.CrossEntropyLoss()(output, y)\n","print(f'损失: {loss.item():.4f}')\n","\n","# 查看梯度（反向传播前）\n","print(f'\\n反向传播前，第一层权重梯度: {model.layers[0].weight.grad}')\n","\n","# 反向传播\n","loss.backward()\n","\n","# 查看梯度（反向传播后）\n","print(f'反向传播后，第一层权重梯度: {model.layers[0].weight.grad}')\n","print(f'梯度形状: {model.layers[0].weight.grad.shape}')\n","print(f'权重形状: {model.layers[0].weight.shape}')"]),

md(["## 4. 第一个训练任务：正弦波分类\n","\n","现在我们来做一个真正的训练任务：**分类两个不同频率的正弦波**。\n","\n","- 输入：一段波形（160个采样点）\n","- 输出：低频(0) 或 高频(1)\n","\n","这是最简单的分类任务——数据可以代码生成，模型2-3层MLP就够了，训练10秒就能收敛。"]),

code(["# 生成数据\n","def generate_sine_wave(freq, duration=0.01, sr=16000, amplitude=0.5):\n","    t = np.linspace(0, duration, int(sr * duration), endpoint=False)\n","    return amplitude * np.sin(2 * np.pi * freq * t)\n","\n","# 低频和高频正弦波\n","low_freq = 200   # 低频类别\n","high_freq = 800  # 高频类别\n","num_samples = 160  # 每个样本的采样点数\n","\n","# 生成训练数据\n","n_train = 500\n","X_train = []\n","y_train = []\n","for _ in range(n_train // 2):\n","    # 低频 + 少量随机扰动\n","    f_low = low_freq + np.random.uniform(-50, 50)\n","    X_train.append(generate_sine_wave(f_low)[:num_samples])\n","    y_train.append(0)\n","    # 高频 + 少量随机扰动\n","    f_high = high_freq + np.random.uniform(-50, 50)\n","    X_train.append(generate_sine_wave(f_high)[:num_samples])\n","    y_train.append(1)\n","\n","X_train = torch.FloatTensor(np.array(X_train))\n","y_train = torch.LongTensor(y_train)\n","\n","print(f'训练数据形状: {X_train.shape}')  # [500, 160]\n","print(f'标签形状: {y_train.shape}')      # [500]\n","print(f'类别0(低频)样本数: {(y_train == 0).sum()}')\n","print(f'类别1(高频)样本数: {(y_train == 1).sum()}')"]),

code(["# 可视化一些样本\n","fig, axes = plt.subplots(1, 2, figsize=(12, 3))\n","t_axis = np.arange(num_samples) / 16000\n","\n","# 低频\n","idx_low = (y_train == 0).nonzero(as_tuple=True)[0][0]\n","axes[0].plot(t_axis * 1000, X_train[idx_low].numpy())\n","axes[0].set_title('低频正弦波 (类别0)')\n","axes[0].set_xlabel('Time (ms)')\n","axes[0].set_ylabel('Amplitude')\n","axes[0].grid(True, alpha=0.3)\n","\n","# 高频\n","idx_high = (y_train == 1).nonzero(as_tuple=True)[0][0]\n","axes[1].plot(t_axis * 1000, X_train[idx_high].numpy())\n","axes[1].set_title('高频正弦波 (类别1)')\n","axes[1].set_xlabel('Time (ms)')\n","axes[1].set_ylabel('Amplitude')\n","axes[1].grid(True, alpha=0.3)\n","\n","plt.tight_layout()\n","plt.show()"]),

md(["### 训练MLP分类器\n","\n","现在用MLP来训练分类器。你需要填空完成训练循环。\n","\n","**填空任务**：完成训练循环中的关键步骤。"]),

code(["# ====== 练习：训练MLP分类器 ======\n","\n","model = SimpleMLP(input_dim=160, hidden_dim=64, output_dim=2)\n","criterion = nn.CrossEntropyLoss()\n","optimizer = torch.optim.Adam(model.parameters(), lr=0.001)\n","\n","# 训练\n","losses = []\n","accuracies = []\n","n_epochs = 50\n","\n","for epoch in range(n_epochs):\n","    # TODO: 前向传播\n","    outputs = model(X_train)\n","    \n","    # TODO: 计算损失\n","    loss = criterion(outputs, y_train)\n","    \n","    # TODO: 反向传播（三步：清零梯度 → 反向传播 → 更新参数）\n","    optimizer.zero_grad()\n","    loss.backward()\n","    optimizer.step()\n","    \n","    # 记录\n","    losses.append(loss.item())\n","    with torch.no_grad():\n","        predictions = outputs.argmax(dim=1)\n","        accuracy = (predictions == y_train).float().mean()\n","        accuracies.append(accuracy.item())\n","    \n","    if (epoch + 1) % 10 == 0:\n","        print(f'Epoch {epoch+1:3d}, Loss: {loss.item():.4f}, Acc: {accuracy.item():.4f}')\n","\n","print(f'\\n最终准确率: {accuracies[-1]:.4f}')"]),

code(["# 可视化训练过程\n","fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n","\n","axes[0].plot(losses)\n","axes[0].set_xlabel('Epoch')\n","axes[0].set_ylabel('Loss')\n","axes[0].set_title('Training Loss')\n","axes[0].grid(True, alpha=0.3)\n","\n","axes[1].plot(accuracies)\n","axes[1].set_xlabel('Epoch')\n","axes[1].set_ylabel('Accuracy')\n","axes[1].set_title('Training Accuracy')\n","axes[1].grid(True, alpha=0.3)\n","\n","plt.tight_layout()\n","plt.show()"]),

md(["### 挑战任务\n","\n","1. 修改 `hidden_dim`，观察对训练速度和准确率的影响（试试16, 64, 256）\n","2. 修改学习率，观察训练曲线的变化（试试0.0001, 0.001, 0.01）\n","3. 增加一个隐藏层，观察是否提升性能\n","4. 尝试将低频和高频的频率靠近（如400 vs 600），观察分类是否变难\n","\n","这些实验只需要改1-2行代码，但能让你对超参数的影响建立直觉。"]),

md(["## 本节要点\n","\n","1. **激活函数**引入非线性——没有它，多层线性变换等于一层\n","2. **ReLU = 半波整流**——你已经懂的信号处理概念！\n","3. **MLP = 多层线性变换 + 激活函数**，是深度网络的基本构建块\n","4. **反向传播** = 自动计算梯度，你只需要 `loss.backward()` + `optimizer.step()`\n","5. **训练循环**：前向传播 → 计算损失 → 清零梯度 → 反向传播 → 更新参数\n"]),

md(["---\n","下一节：[03-cnn-audio.ipynb](03-cnn-audio.ipynb) — CNN与声音的\"图像化\"\n"]),
]

# ============================================================
# 03-cnn-audio.ipynb
# ============================================================
nb3 = [
md(["# CNN与声音的\"图像化\"\n","\n","## 学习目标\n","\n","- 理解语谱图(spectrogram)：音频可以变成\"图像\"\n","- 理解卷积操作在频谱图上的含义\n","- 能用PyTorch搭建并训练一个CNN\n","- 完成主线项目第一阶段：语音vs噪声分类\n"]),

md(["## 1. 音频的三种表示\n","\n","音频信号可以用三种方式表示：\n","1. **时域**：振幅随时间变化（波形）\n","2. **频域**：各频率成分的强度（频谱）\n","3. **时频域**：频率成分随时间的变化（语谱图）\n","\n","语谱图是深度学习处理音频最常用的表示方式。"]),

code(["import numpy as np\n","import matplotlib.pyplot as plt\n","import torch\n","import torch.nn as nn\n","import torchaudio\n","\n","plt.rcParams['font.size'] = 12\n","\n","# 生成模拟信号：440Hz正弦波 + 880Hz正弦波（后半段）\n","sr = 16000\n","duration = 1.0\n","t = np.linspace(0, duration, int(sr * duration), endpoint=False)\n","\n","signal_low = 0.5 * np.sin(2 * np.pi * 440 * t)    # 低频，全程\n","signal_high = np.zeros_like(t)\n","signal_high[len(t)//2:] = 0.3 * np.sin(2 * np.pi * 880 * t[len(t)//2:])  # 高频，后半段\n","signal = signal_low + signal_high\n","\n","fig, axes = plt.subplots(1, 3, figsize=(16, 4))\n","\n","# 时域\n","axes[0].plot(t[:2000], signal[:2000])\n","axes[0].set_xlabel('Time (s)')\n","axes[0].set_ylabel('Amplitude')\n","axes[0].set_title('时域：波形')\n","axes[0].grid(True, alpha=0.3)\n","\n","# 频域\n","spectrum = np.abs(np.fft.rfft(signal))\n","freqs = np.fft.rfftfreq(len(signal), 1/sr)\n","axes[1].plot(freqs[:2000], spectrum[:2000])\n","axes[1].set_xlabel('Frequency (Hz)')\n","axes[2].set_ylabel('Magnitude')\n","axes[1].set_title('频域：频谱')\n","axes[1].grid(True, alpha=0.3)\n","\n","# 时频域（语谱图）\n","from scipy.signal import spectrogram as scipy_spectrogram\n","f, t_spec, Sxx = scipy_spectrogram(signal, sr, nperseg=256)\n","axes[2].pcolormesh(t_spec, f, 10 * np.log10(Sxx + 1e-10), shading='gouraud')\n","axes[2].set_ylabel('Frequency (Hz)')\n","axes[2].set_xlabel('Time (s)')\n","axes[2].set_title('时频域：语谱图')\n","axes[2].set_ylim(0, 2000)\n","\n","plt.tight_layout()\n","plt.show()"]),

md(["### 语谱图：深度学习处理音频的关键\n","\n","语谱图横轴是时间，纵轴是频率，颜色是能量。\n","\n","**关键洞察**：语谱图就是一张\"图片\"！CNN天生擅长处理2D图片的模式识别。\n","\n","所以处理音频的思路是：\n","1. 把音频变成语谱图\n","2. 用CNN处理语谱图\n","\n","这就像给声音\"拍照\"，然后用图像识别的方法来分析。"]),

md(["## 2. 语谱图的细节\n","\n","### 梅尔语谱图(Mel Spectrogram)\n","\n","梅尔刻度模拟了人耳对频率的感知——低频区域分辨率高，高频区域分辨率低。\n","这与CI的电极映射有内在联系：CI的低频电极对应更多频率信息。\n","\n","梅尔语谱图是音频深度学习中最常用的特征表示。"]),

code(["# 用torchaudio提取梅尔语谱图\n","import torchaudio.transforms as T\n","\n","# 生成一段模拟语音信号\n","sr = 16000\n","duration = 1.0\n","t = np.linspace(0, duration, int(sr * duration), endpoint=False)\n","waveform = torch.FloatTensor(0.3 * np.sin(2*np.pi*300*t) + 0.2 * np.sin(2*np.pi*600*t) + 0.1 * np.random.randn(len(t)))\n","waveform = waveform.unsqueeze(0)  # [1, num_samples]\n","\n","# 提取梅尔语谱图\n","mel_transform = T.MelSpectrogram(\n","    sample_rate=sr,\n","    n_fft=512,           # FFT窗口大小\n","    hop_length=160,      # 帧移\n","    n_mels=64,           # 梅尔频带数\n",")\n","\n","mel_spec = mel_transform(waveform)  # [1, n_mels, time_frames]\n","mel_spec_db = torchaudio.functional.amplitude_to_DB(mel_spec, top_db=80)\n","\n","print(f'波形形状: {waveform.shape}')\n","print(f'梅尔语谱图形状: {mel_spec_db.shape}')\n","print(f'梅尔频带数: {mel_spec_db.shape[1]}')\n","print(f'时间帧数: {mel_spec_db.shape[2]}')\n","\n","# 可视化\n","plt.figure(figsize=(10, 4))\n","plt.imshow(mel_spec_db[0].numpy(), aspect='auto', origin='lower', cmap='viridis')\n","plt.colorbar(label='Magnitude (dB)')\n","plt.xlabel('Time Frame')\n","plt.ylabel('Mel Band')\n","plt.title('Mel Spectrogram')\n","plt.tight_layout()\n","plt.show()"]),

md(["### 不同类型声音的语谱图对比\n","\n","下面展示纯净语音、噪声、带噪语音三种语谱图的对比。\n","理解这个对比对于后续的语音增强（模块5）至关重要。"]),

code(["# 生成三种信号并对比\n","np.random.seed(42)\n","sr = 16000\n","duration = 0.5\n","n_samples = int(sr * duration)\n","t = np.linspace(0, duration, n_samples, endpoint=False)\n","\n","# 纯净语音模拟：多个谐波\n","clean = sum(0.3/k * np.sin(2*np.pi*200*k*t) for k in range(1, 6))\n","# 噪声\n","noise = 0.1 * np.random.randn(n_samples)\n","# 带噪语音\n","noisy = clean + noise\n","\n","fig, axes = plt.subplots(3, 2, figsize=(14, 8))\n","\n","mel_transform = T.MelSpectrogram(sample_rate=sr, n_fft=512, hop_length=160, n_mels=64)\n","\n","for i, (sig, name) in enumerate([(clean, '纯净语音'), (noise, '噪声'), (noisy, '带噪语音')]):\n","    # 波形\n","    axes[i, 0].plot(t[:2000], sig[:2000])\n","    axes[i, 0].set_ylabel('Amplitude')\n","    axes[i, 0].set_title(f'{name} - 波形')\n","    axes[i, 0].grid(True, alpha=0.3)\n","    \n","    # 语谱图\n","    sig_tensor = torch.FloatTensor(sig).unsqueeze(0)\n","    mel = torchaudio.functional.amplitude_to_DB(mel_transform(sig_tensor), top_db=80)\n","    axes[i, 1].imshow(mel[0].numpy(), aspect='auto', origin='lower', cmap='viridis')\n","    axes[i, 1].set_title(f'{name} - 语谱图')\n","    axes[i, 1].set_ylabel('Mel Band')\n","\n","axes[2, 0].set_xlabel('Time (s)')\n","axes[2, 1].set_xlabel('Time Frame')\n","plt.tight_layout()\n","plt.show()\n","\n","print('观察：语音的语谱图有清晰的条纹结构，噪声的语谱图是均匀分布的。')\n","print('语音增强的目标就是：把带噪语音的语谱图\"变干净\"——去除均匀的噪声，保留清晰的条纹。')"]),

md(["## 3. 卷积神经网络(CNN)\n","\n","### 3.1 卷积操作\n","\n","卷积在语谱图上的直觉：一个小窗口（卷积核）在语谱图上滑动，提取局部时频模式。\n","\n","- **卷积核** = 一个小的模式检测器\n","- **步长(stride)** = 每次滑动的距离\n","- **填充(padding)** = 在边缘补零，保持输出尺寸"]),

code(["# CNN核心操作演示\n","import torch.nn.functional as F\n","\n","# 创建一个简单的8x8语谱图\n","spec = torch.randn(1, 1, 8, 8)  # [batch, channel, height, width]\n","\n","# 3x3卷积核\n","conv = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=0)\n","\n","output = conv(spec)\n","print(f'输入形状: {spec.shape}')\n","print(f'输出形状: {output.shape}')\n","print(f'3x3卷积，无填充: 8→6 (8-3+1=6)')\n","\n","# 加入填充\n","conv_pad = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=1)\n","output_pad = conv_pad(spec)\n","print(f'\\n加入padding=1后输出形状: {output_pad.shape}')\n","print(f'3x3卷积，padding=1: 8→8 (尺寸不变)')\n","\n","# 步长为2\n","conv_stride = nn.Conv2d(1, 1, kernel_size=3, stride=2, padding=1)\n","output_stride = conv_stride(spec)\n","print(f'\\nstride=2后输出形状: {output_stride.shape}')\n","print(f'3x3卷积，stride=2，padding=1: 8→4 (尺寸减半)')"]),

md(["### 3.2 池化(Pooling)\n","\n","池化操作减小特征图的尺寸，保留最重要的信息。"]),

code(["# 池化演示\n","x = torch.randn(1, 1, 4, 4)\n","print('输入:')\n","print(x[0, 0].numpy())\n","\n","# 最大池化\n","maxpool = nn.MaxPool2d(kernel_size=2, stride=2)\n","y = maxpool(x)\n","print(f'\\n最大池化后形状: {y.shape}')\n","print('输出:')\n","print(y[0, 0].numpy())\n","print('\\n每个2x2区域取最大值，尺寸减半')"]),

md(["## 4. 搭建CNN音频分类器\n","\n","现在我们搭建一个CNN来分类语谱图：**语音 vs 噪声**。\n","\n","这是主线项目的第一阶段。"]),

code(["# 生成语音/噪声分类数据集\n","import torch\n","from torch.utils.data import Dataset, DataLoader\n","\n","class SpeechNoiseDataset(Dataset):\n","    \"\"\"语音/噪声分类数据集\"\"\"\n","    def __init__(self, n_samples=800, sr=16000, duration=0.5):\n","        self.sr = sr\n","        self.duration = duration\n","        self.n_samples = n_samples\n","        \n","        # 预生成数据\n","        self.data = []\n","        self.labels = []\n","        n_samples_signal = int(sr * duration)\n","        \n","        for i in range(n_samples):\n","            t = np.linspace(0, duration, n_samples_signal, endpoint=False)\n","            \n","            if i < n_samples // 2:\n","                # 语音：多个谐波\n","                freq = np.random.uniform(100, 400)\n","                signal = sum(np.random.uniform(0.1, 0.4) * np.sin(2*np.pi*freq*k*t) for k in range(1, np.random.randint(3, 7)))\n","                signal += 0.02 * np.random.randn(n_samples_signal)  # 微弱噪声\n","                label = 0  # 语音\n","            else:\n","                # 噪声：白噪声或粉红噪声\n","                signal = np.random.uniform(0.05, 0.3) * np.random.randn(n_samples_signal)\n","                label = 1  # 噪声\n","            \n","            self.data.append(torch.FloatTensor(signal))\n","            self.labels.append(label)\n","    \n","    def __len__(self):\n","        return self.n_samples\n","    \n","    def __getitem__(self, idx):\n","        return self.data[idx], self.labels[idx]\n","\n","# 创建数据集\n","dataset = SpeechNoiseDataset(n_samples=800)\n","print(f'数据集大小: {len(dataset)}')\n","print(f'语音样本数: {sum(1 for l in dataset.labels if l == 0)}')\n","print(f'噪声样本数: {sum(1 for l in dataset.labels if l == 1)}')\n","\n","# 划分训练/验证集\n","train_size = int(0.8 * len(dataset))\n","val_size = len(dataset) - train_size\n","train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size])\n","print(f'训练集: {train_size}, 验证集: {val_size}')"]),

md(["### 搭建CNN模型\n","\n","你需要自己填写一些关键参数。"]),

code(["# ====== 练习：搭建CNN ======\n","\n","class AudioCNN(nn.Module):\n","    def __init__(self, n_mels=64, n_classes=2):\n","        super().__init__()\n","        self.mel_transform = T.MelSpectrogram(\n","            sample_rate=16000,\n","            n_fft=512,\n","            hop_length=160,\n","            n_mels=n_mels,\n","        )\n","        \n","        # TODO: 定义卷积层\n","        # 提示：输入是 [batch, 1, n_mels, time_frames]\n","        self.features = nn.Sequential(\n","            nn.Conv2d(1, 16, kernel_size=3, padding=1),   # [B, 16, n_mels, T]\n","            nn.ReLU(),\n","            nn.MaxPool2d(2),                               # [B, 16, n_mels/2, T/2]\n","            nn.Conv2d(16, 32, kernel_size=3, padding=1),  # [B, 32, n_mels/2, T/2]\n","            nn.ReLU(),\n","            nn.MaxPool2d(2),                               # [B, 32, n_mels/4, T/4]\n","            nn.Conv2d(32, 64, kernel_size=3, padding=1),  # [B, 64, n_mels/4, T/4]\n","            nn.ReLU(),\n","            nn.AdaptiveAvgPool2d((1, 1)),                  # [B, 64, 1, 1] 全局平均池化\n","        )\n","        \n","        # TODO: 定义分类器\n","        self.classifier = nn.Linear(64, n_classes)\n","    \n","    def forward(self, x):\n","        # x: [batch, num_samples]\n","        # 提取梅尔语谱图\n","        mel = self.mel_transform(x)            # [B, 1, n_mels, T]\n","        mel_db = torchaudio.functional.amplitude_to_DB(mel, top_db=80)\n","        mel_db = (mel_db - mel_db.mean()) / (mel_db.std() + 1e-8)  # 归一化\n","        mel_db = mel_db.unsqueeze(1)           # [B, 1, n_mels, T] 添加通道维\n","        \n","        # 卷积特征提取\n","        features = self.features(mel_db)       # [B, 64, 1, 1]\n","        features = features.view(features.size(0), -1)  # [B, 64]\n","        \n","        # 分类\n","        output = self.classifier(features)     # [B, n_classes]\n","        return output\n","\n","# 测试模型\n","model = AudioCNN()\n","test_input = torch.randn(4, 8000)  # batch=4, 0.5秒音频\n","test_output = model(test_input)\n","print(f'输入形状: {test_input.shape}')\n","print(f'输出形状: {test_output.shape}')\n","print(f'模型参数总数: {sum(p.numel() for p in model.parameters()):,}')"]),

md(["### 训练CNN\n","\n","现在训练这个CNN分类器。这次你要自己写训练循环的部分代码。"]),

code(["# ====== 练习：训练CNN ======\n","\n","device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n","model = AudioCNN().to(device)\n","criterion = nn.CrossEntropyLoss()\n","optimizer = torch.optim.Adam(model.parameters(), lr=0.001)\n","\n","train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)\n","val_loader = DataLoader(val_dataset, batch_size=32)\n","\n","# 训练\n","n_epochs = 20\n","train_losses = []\n","val_accs = []\n","\n","for epoch in range(n_epochs):\n","    model.train()\n","    epoch_loss = 0\n","    for batch_x, batch_y in train_loader:\n","        batch_x, batch_y = batch_x.to(device), batch_y.to(device)\n","        \n","        # TODO: 完成训练循环\n","        outputs = model(batch_x)\n","        loss = criterion(outputs, batch_y)\n","        optimizer.zero_grad()\n","        loss.backward()\n","        optimizer.step()\n","        \n","        epoch_loss += loss.item()\n","    \n","    train_losses.append(epoch_loss / len(train_loader))\n","    \n","    # 验证\n","    model.eval()\n","    correct = 0\n","    total = 0\n","    with torch.no_grad():\n","        for batch_x, batch_y in val_loader:\n","            batch_x, batch_y = batch_x.to(device), batch_y.to(device)\n","            outputs = model(batch_x)\n","            _, predicted = outputs.max(1)\n","            total += batch_y.size(0)\n","            correct += predicted.eq(batch_y).sum().item()\n","    \n","    val_acc = correct / total\n","    val_accs.append(val_acc)\n","    \n","    if (epoch + 1) % 5 == 0:\n","        print(f'Epoch {epoch+1:2d}, Loss: {train_losses[-1]:.4f}, Val Acc: {val_acc:.4f}')\n","\n","print(f'\\n最终验证准确率: {val_accs[-1]:.4f}')"]),

code(["# 可视化训练过程\n","fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n","\n","axes[0].plot(train_losses)\n","axes[0].set_xlabel('Epoch')\n","axes[0].set_ylabel('Loss')\n","axes[0].set_title('Training Loss')\n","axes[0].grid(True, alpha=0.3)\n","\n","axes[1].plot(val_accs)\n","axes[1].set_xlabel('Epoch')\n","axes[1].set_ylabel('Accuracy')\n","axes[1].set_title('Validation Accuracy')\n","axes[1].grid(True, alpha=0.3)\n","\n","plt.tight_layout()\n","plt.show()"]),

md(["### 挑战任务\n","\n","1. 修改CNN结构：增加/减少卷积层，观察效果\n","2. 修改 `n_mels`（32, 64, 128），观察对准确率和训练速度的影响\n","3. 用 `nn.Sequential` 替换手动定义的 `features`，比较代码可读性\n","4. 增加一个 `nn.Dropout(0.5)` 层在分类器之前，观察是否缓解过拟合"]),

md(["## 本节要点\n","\n","1. **语谱图**是音频深度学习的核心表示——横轴时间、纵轴频率、颜色能量\n","2. **梅尔语谱图**模拟人耳感知——与CI电极映射有内在联系\n","3. **CNN处理音频 = CNN处理语谱图\"图片\"**\n","4. **卷积**= 模式检测器在语谱图上滑动，寻找局部时频模式\n","5. **池化**= 减小特征图尺寸，保留重要信息\n","6. 训练CNN的完整流程：数据 → 特征提取 → 模型 → 训练 → 评估\n"]),

md(["---\n","下一节：[04-training-tricks.ipynb](04-training-tricks.ipynb) — 训练技巧与实验方法论\n"]),
]

# ============================================================
# 04-training-tricks.ipynb
# ============================================================
nb4 = [
md(["# 训练技巧与实验方法论\n","\n","## 学习目标\n","\n","- 理解过拟合/欠拟合，学会用训练/验证集检测\n","- 掌握学习率、批大小、优化器的选择\n","- 掌握音频数据增强方法\n","- 学会用TensorBoard记录实验\n","- 这是\"能跑通\"到\"能做研究\"的关键一步\n"]),

md(["## 1. 过拟合与欠拟合\n","\n","**过拟合**：模型在训练集上表现好，但在验证集上表现差——\"死记硬背\"。\n","**欠拟合**：模型在训练集上就表现不好——\"没学够\"。\n","\n","我们来做一个实验：把训练集缩小到10个样本，观察过拟合。"]),

code(["import numpy as np\n","import matplotlib.pyplot as plt\n","import torch\n","import torch.nn as nn\n","from torch.utils.data import DataLoader, Subset\n","import torchaudio.transforms as T\n","import torchaudio\n","\n","plt.rcParams['font.size'] = 12\n","\n","# 复用上节课的数据集和模型\n","from importlib.util import spec_from_file_location\n","# 直接重新定义（确保notebook自包含）\n","\n","class SpeechNoiseDataset(torch.utils.data.Dataset):\n","    def __init__(self, n_samples=800, sr=16000, duration=0.5):\n","        self.sr = sr\n","        self.data = []\n","        self.labels = []\n","        n_sig = int(sr * duration)\n","        for i in range(n_samples):\n","            t = np.linspace(0, duration, n_sig, endpoint=False)\n","            if i < n_samples // 2:\n","                freq = np.random.uniform(100, 400)\n","                signal = sum(np.random.uniform(0.1, 0.4) * np.sin(2*np.pi*freq*k*t) for k in range(1, np.random.randint(3, 7)))\n","                signal += 0.02 * np.random.randn(n_sig)\n","                label = 0\n","            else:\n","                signal = np.random.uniform(0.05, 0.3) * np.random.randn(n_sig)\n","                label = 1\n","            self.data.append(torch.FloatTensor(signal))\n","            self.labels.append(label)\n","    def __len__(self): return len(self.data)\n","    def __getitem__(self, idx): return self.data[idx], self.labels[idx]\n","\n","class AudioCNN(nn.Module):\n","    def __init__(self, n_mels=64, n_classes=2):\n","        super().__init__()\n","        self.mel_transform = T.MelSpectrogram(sample_rate=16000, n_fft=512, hop_length=160, n_mels=n_mels)\n","        self.features = nn.Sequential(\n","            nn.Conv2d(1, 16, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n","            nn.Conv2d(16, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n","            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.AdaptiveAvgPool2d((1, 1)),\n","        )\n","        self.classifier = nn.Linear(64, n_classes)\n","    def forward(self, x):\n","        mel = self.mel_transform(x)\n","        mel_db = torchaudio.functional.amplitude_to_DB(mel, top_db=80)\n","        mel_db = (mel_db - mel_db.mean()) / (mel_db.std() + 1e-8)\n","        mel_db = mel_db.unsqueeze(1)\n","        f = self.features(mel_db).view(x.size(0), -1)\n","        return self.classifier(f)\n","\n","print('数据和模型准备完成')"]),

code(["# ====== 过拟合实验：缩小训练集 ======\n","np.random.seed(42)\n","torch.manual_seed(42)\n","\n","full_dataset = SpeechNoiseDataset(n_samples=800)\n","train_size = int(0.8 * len(full_dataset))\n","val_size = len(full_dataset) - train_size\n","train_dataset_full, val_dataset = torch.utils.data.random_split(full_dataset, [train_size, val_size])\n","\n","# 正常训练集 vs 极小训练集\n","train_dataset_small = Subset(train_dataset_full, range(10))  # 只有10个样本！\n","\n","def train_model(train_ds, val_ds, epochs=30, lr=0.001):\n","    model = AudioCNN()\n","    criterion = nn.CrossEntropyLoss()\n","    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n","    train_loader = DataLoader(train_ds, batch_size=16, shuffle=True)\n","    val_loader = DataLoader(val_ds, batch_size=32)\n","    \n","    train_losses, val_losses = [], []\n","    train_accs, val_accs = [], []\n","    \n","    for epoch in range(epochs):\n","        model.train()\n","        t_loss, t_correct, t_total = 0, 0, 0\n","        for x, y in train_loader:\n","            out = model(x)\n","            loss = criterion(out, y)\n","            optimizer.zero_grad(); loss.backward(); optimizer.step()\n","            t_loss += loss.item()\n","            t_correct += (out.argmax(1) == y).sum().item()\n","            t_total += y.size(0)\n","        train_losses.append(t_loss / len(train_loader))\n","        train_accs.append(t_correct / t_total)\n","        \n","        model.eval()\n","        v_loss, v_correct, v_total = 0, 0, 0\n","        with torch.no_grad():\n","            for x, y in val_loader:\n","                out = model(x)\n","                v_loss += criterion(out, y).item()\n","                v_correct += (out.argmax(1) == y).sum().item()\n","                v_total += y.size(0)\n","        val_losses.append(v_loss / len(val_loader))\n","        val_accs.append(v_correct / v_total)\n","    \n","    return train_losses, val_losses, train_accs, val_accs\n","\n","# 训练两个模型\n","print('训练正常数据量模型...')\n","tl_full, vl_full, ta_full, va_full = train_model(train_dataset_full, val_dataset)\n","print('训练极小数据量模型...')\n","tl_small, vl_small, ta_small, va_small = train_model(train_dataset_small, val_dataset)"]),

code(["# 对比过拟合 vs 正常训练\n","fig, axes = plt.subplots(2, 2, figsize=(14, 8))\n","\n","axes[0, 0].plot(tl_full, label='Train'); axes[0, 0].plot(vl_full, label='Val')\n","axes[0, 0].set_title('正常数据 - Loss'); axes[0, 0].legend(); axes[0, 0].grid(True, alpha=0.3)\n","\n","axes[0, 1].plot(ta_full, label='Train'); axes[0, 1].plot(va_full, label='Val')\n","axes[0, 1].set_title('正常数据 - Accuracy'); axes[0, 1].legend(); axes[0, 1].grid(True, alpha=0.3)\n","\n","axes[1, 0].plot(tl_small, label='Train'); axes[1, 0].plot(vl_small, label='Val')\n","axes[1, 0].set_title('极小数据(10样本) - Loss'); axes[1, 0].legend(); axes[1, 0].grid(True, alpha=0.3)\n","\n","axes[1, 1].plot(ta_small, label='Train'); axes[1, 1].plot(va_small, label='Val')\n","axes[1, 1].set_title('极小数据(10样本) - Accuracy'); axes[1, 1].legend(); axes[1, 1].grid(True, alpha=0.3)\n","\n","plt.tight_layout()\n","plt.show()\n","print('\\n观察：极小数据时，训练loss很低但验证loss很高 → 过拟合！')"]),

md(["### 对抗过拟合的方法\n","\n","1. **更多数据**——最有效\n","2. **数据增强**——等价于增加数据\n","3. **Dropout**——随机丢弃神经元，防止过拟合\n","4. **权重衰减(L2正则)**——限制参数大小\n","5. **早停(Early Stopping)**——验证集性能不再提升时停止训练"]),

md(["## 2. 学习率、批大小、优化器\n","\n","### 2.1 学习率的影响\n","\n","学习率是最重要的超参数。我们来实验不同的学习率。"]),

code(["# 学习率实验\n","lrs = [0.0001, 0.001, 0.01, 0.1]\n","results = {}\n","\n","for lr in lrs:\n","    print(f'训练 lr={lr}...')\n","    tl, vl, ta, va = train_model(train_dataset_full, val_dataset, epochs=20, lr=lr)\n","    results[lr] = (tl, vl, ta, va)\n","\n","# 可视化\n","fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n","for lr in lrs:\n","    tl, vl, ta, va = results[lr]\n","    axes[0].plot(tl, label=f'lr={lr}')\n","    axes[1].plot(va, label=f'lr={lr}')\n","axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Train Loss'); axes[0].set_title('Training Loss')\n","axes[0].legend(); axes[0].grid(True, alpha=0.3)\n","axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Val Accuracy'); axes[1].set_title('Validation Accuracy')\n","axes[1].legend(); axes[1].grid(True, alpha=0.3)\n","plt.tight_layout()\n","plt.show()\n","print('\\n观察：lr太小→训练慢，lr太大→震荡或不收敛')"]),

md(["### 2.2 优化器选择\n","\n","| 优化器 | 特点 | 推荐场景 |\n","|--------|------|----------|\n","| SGD | 简单，需要仔细调学习率 | 大规模训练，精调 |\n","| SGD+Momentum | 加速收敛 | 通用 |\n","| Adam | 自适应学习率，收敛快 | **默认选择**，研究初期 |\n","| AdamW | Adam + 权重衰减，更好泛化 | Transformer等大模型 |\n","\n","**建议**：初期用Adam(lr=0.001)，后期如果需要精调，换成SGD+Momentum。"]),

md(["## 3. 音频数据增强\n","\n","数据增强是提高模型泛化能力的重要手段，尤其在数据量有限时。\n","\n","音频领域常用的增强方法：\n","1. **加噪**——模拟真实环境中的噪声\n","2. **时间拉伸**——改变语速\n","3. **频谱掩蔽(SpecAugment)**——遮住部分时间或频率区域\n","\n","这些方法直接对接后续的DeepFilterNet模块——语音增强本质上就是在做\"去噪\"。"]),

code(["# 音频数据增强演示\n","import torchaudio.transforms as T\n","\n","# 生成一段模拟语音\n","sr = 16000\n","duration = 1.0\n","n_samples = int(sr * duration)\n","t = np.linspace(0, duration, n_samples, endpoint=False)\n","clean_signal = sum(0.3/k * np.sin(2*np.pi*200*k*t) for k in range(1, 5))\n","clean_tensor = torch.FloatTensor(clean_signal).unsqueeze(0)\n","\n","# 1. 加噪\n","noise = 0.1 * torch.randn_like(clean_tensor)\n","noisy_signal = clean_tensor + noise\n","\n","# 2. 频谱掩蔽 (SpecAugment)\n","mel_transform = T.MelSpectrogram(sample_rate=sr, n_fft=512, hop_length=160, n_mels=64)\n","mel = mel_transform(clean_tensor)\n","\n","freq_mask = T.FrequencyMasking(freq_mask_param=10)\n","time_mask = T.TimeMasking(time_mask_param=20)\n","mel_freq_masked = freq_mask(mel)\n","mel_time_masked = time_mask(mel)\n","mel_both_masked = time_mask(freq_mask(mel))\n","\n","# 可视化\n","fig, axes = plt.subplots(1, 5, figsize=(20, 3))\n","titles = ['原始语谱图', '加噪', '频率掩蔽', '时间掩蔽', '频率+时间掩蔽']\n","mel_to_show = [\n","    torchaudio.functional.amplitude_to_DB(mel, top_db=80),\n","    torchaudio.functional.amplitude_to_DB(mel_transform(noisy_signal), top_db=80),\n","    torchaudio.functional.amplitude_to_DB(mel_freq_masked, top_db=80),\n","    torchaudio.functional.amplitude_to_DB(mel_time_masked, top_db=80),\n","    torchaudio.functional.amplitude_to_DB(mel_both_masked, top_db=80),\n","]\n","for ax, m, title in zip(axes, mel_to_show, titles):\n","    ax.imshow(m[0].numpy(), aspect='auto', origin='lower', cmap='viridis')\n","    ax.set_title(title)\n","    ax.set_ylabel('Mel Band') if ax == axes[0] else None\n","    ax.set_xlabel('Time Frame')\n","plt.tight_layout()\n","plt.show()"]),

md(["## 4. 实验管理：TensorBoard\n","\n","在做研究时，每次实验都要记录——做了什么改动、效果如何。\n","**不做记录的实验等于没做。**\n","\n","TensorBoard是PyTorch最常用的实验记录工具。"]),

code(["# TensorBoard使用示例\n","from torch.utils.tensorboard import SummaryWriter\n","\n","# 创建writer\n","writer = SummaryWriter('runs/experiment_1')\n","\n","# 在训练循环中记录\n","model = AudioCNN()\n","optimizer = torch.optim.Adam(model.parameters(), lr=0.001)\n","criterion = nn.CrossEntropyLoss()\n","train_loader = DataLoader(train_dataset_full, batch_size=32, shuffle=True)\n","\n","# 训练5个epoch做演示\n","for epoch in range(5):\n","    model.train()\n","    total_loss = 0\n","    for batch_x, batch_y in train_loader:\n","        out = model(batch_x)\n","        loss = criterion(out, batch_y)\n","        optimizer.zero_grad(); loss.backward(); optimizer.step()\n","        total_loss += loss.item()\n","    \n","    # 记录到TensorBoard\n","    writer.add_scalar('Loss/train', total_loss / len(train_loader), epoch)\n","    writer.add_scalar('Learning_Rate', optimizer.param_groups[0]['lr'], epoch)\n","\n","writer.close()\n","print('TensorBoard日志已写入 runs/experiment_1')\n","print('在终端运行: tensorboard --logdir=runs')\n","print('然后在浏览器打开: http://localhost:6006')"]),

md(["### TensorBoard最佳实践\n","\n","1. **每次实验用不同的文件夹**：`runs/lr_0.001`, `runs/lr_0.0001`\n","2. **记录所有超参数**：学习率、批大小、模型结构\n","3. **记录训练和验证的loss和accuracy**\n","4. **记录学习率变化**（如果用了scheduler）\n","5. **记录模型结构**：`writer.add_graph(model, input)`"]),

md(["## 本节要点\n","\n","1. **过拟合**= 训练集好但验证集差 → 解决方法：更多数据、数据增强、Dropout、早停\n","2. **学习率**是最重要的超参数——太大震荡，太小慢\n","3. **Adam(lr=0.001)** 是研究初期的默认选择\n","4. **数据增强**对音频尤其重要：加噪、时间拉伸、频谱掩蔽\n","5. **实验必须记录**——TensorBoard是最常用的工具\n","6. **训练/验证/测试集划分**是做研究的基本规范\n"]),

md(["---\n","返回目录：[README.md](../README.md)"]),
]

write("01-linear-regression.ipynb", nb1)
write("02-mlp-pytorch.ipynb", nb2)
write("03-cnn-audio.ipynb", nb3)
write("04-training-tricks.ipynb", nb4)
print("\n模块2全部notebook生成完成！")
