#!/usr/bin/env python3
"""生成模块0的全部Jupyter notebook"""
import json
import os

NOTEBOOK_DIR = os.path.dirname(os.path.abspath(__file__))

def make_notebook(cells):
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "cells": cells
    }

def md(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source if isinstance(source, list) else [source]
    }

def code(source):
    return {
        "cell_type": "code",
        "metadata": {},
        "source": source if isinstance(source, list) else [source],
        "execution_count": None,
        "outputs": []
    }

def write_notebook(filename, cells):
    nb = make_notebook(cells)
    path = os.path.join(NOTEBOOK_DIR, filename)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)
    print(f"Written: {path}")


# ============================================================
# Notebook 1: Python基础——从计算器到程序
# ============================================================
nb1_cells = [
    md(["# Python基础——从计算器到程序\n",
        "\n",
        "## 学习目标\n",
        "\n",
        "- 理解Python从\"计算器式脚本\"到\"程序化思维\"的转变\n",
        "- 掌握变量、数据类型、运算的基本用法\n",
        "- 用NumPy生成和操作数组，理解向量化思维\n",
        "- 掌握控制流（if/for/while）的基本用法\n",
        "- **重点**：理解为什么要写函数，从\"复制粘贴\"到\"函数调用\"\n",
        "- 掌握列表和字典的基本操作\n",
        "\n",
        "## 本节约定\n",
        "\n",
        "所有练习都使用**音频信号**作为素材：\n",
        "- 不用斐波那契数列学循环——用\"生成不同频率的正弦波\"学循环\n",
        "- 不用学生成绩单学字典——用\"音频文件的元数据\"学字典\n",
        "- 不用字符串反转学函数——用\"信号生成与处理\"学函数\n"]),

    md(["## 1. Python环境确认\n",
        "\n",
        "首先确认你的Python环境和必要的库已经安装好。"]),

    code("import sys\nprint(f'Python版本: {sys.version}')"),

    code(["import numpy as np\n",
          "import matplotlib.pyplot as plt\n",
          "import scipy.signal as signal\n",
          "print('所有库导入成功！')"]),

    md(["## 2. 变量、数据类型与运算\n",
        "\n",
        "### 2.1 变量\n",
        "\n",
        "在音频处理中，我们用变量来存储音频的基本参数。"]),

    code(["# 音频基本参数\n",
          "sample_rate = 16000       # 采样率 (Hz)\n",
          "duration = 1.0            # 时长 (秒)\n",
          "frequency = 440.0         # 频率 (Hz) — A4音\n",
          "amplitude = 0.5           # 振幅\n",
          "\n",
          "print(f'采样率: {sample_rate} Hz')\n",
          "print(f'时长: {duration} 秒')\n",
          "print(f'频率: {frequency} Hz (A4音)')\n",
          "print(f'振幅: {amplitude}')"]),

    md(["### 2.2 数据类型\n",
        "\n",
        "Python的基本数据类型：\n",
        "- `int`：整数（如采样率16000）\n",
        "- `float`：浮点数（如频率440.0）\n",
        "- `str`：字符串（如文件名\"speech.wav\"）\n",
        "- `bool`：布尔值（如 is_speech = True）"]),

    code(["# 数据类型示例\n",
          "sample_rate = 16000        # int\n",
          "frequency = 440.0          # float\n",
          "filename = 'speech.wav'    # str\n",
          "is_speech = True           # bool\n",
          "\n",
          "print(f'type(sample_rate) = {type(sample_rate)}')\n",
          "print(f'type(frequency) = {type(frequency)}')\n",
          "print(f'type(filename) = {type(filename)}')\n",
          "print(f'type(is_speech) = {type(is_speech)}')"]),

    md(["### 2.3 运算\n",
        "\n",
        "音频处理中的常见运算："]),

    code(["# 计算音频信号的总样本数\n",
          "num_samples = int(sample_rate * duration)\n",
          "print(f'总样本数: {num_samples}')\n",
          "\n",
          "# 计算每个周期的样本数\n",
          "samples_per_cycle = sample_rate / frequency\n",
          "print(f'每个周期的样本数: {samples_per_cycle:.2f}')\n",
          "\n",
          "# 分贝转换\n",
          "import math\n",
          "db = 20 * math.log10(amplitude)\n",
          "print(f'振幅 {amplitude} 对应 {db:.1f} dB')"]),

    md(["## 3. NumPy数组：从标量到向量\n",
        "\n",
        "**关键概念**：音频信号就是一组数字（数组），NumPy让我们可以像写数学公式一样操作整个数组，而不是逐个元素循环。\n",
        "\n",
        "这就是\"向量化思维\"——物理背景的学生应该很容易理解，这就像向量运算和标量运算的区别。"]),

    code(["# 生成时间轴\n",
          "t = np.linspace(0, duration, num_samples, endpoint=False)\n",
          "print(f'时间轴长度: {len(t)}')\n",
          "print(f'前5个时间点: {t[:5]}')"]),

    code(["# 生成正弦波：纯音（A4 = 440 Hz）\n",
          "sine_wave = amplitude * np.sin(2 * np.pi * frequency * t)\n",
          "print(f'波形长度: {len(sine_wave)}')\n",
          "print(f'前5个样本值: {sine_wave[:5]}')"]),

    code(["# 可视化\n",
          "plt.figure(figsize=(12, 4))\n",
          "plt.plot(t[:500], sine_wave[:500])  # 只画前500个样本\n",
          "plt.xlabel('Time (s)')\n",
          "plt.ylabel('Amplitude')\n",
          "plt.title(f'Sine Wave: {frequency} Hz, Amplitude: {amplitude}')\n",
          "plt.grid(True)\n",
          "plt.show()"]),

    md(["### 练习1：向量化运算\n",
        "\n",
        "NumPy的强大之处在于可以对整个数组做运算，不需要循环。\n",
        "\n",
        "**任务**：生成两个不同频率的正弦波，将它们相加，得到一个复合波。"]),

    code(["# ===== 练习1：向量化运算 =====\n",
          "# 提示：\n",
          "# 1. 生成一个 261.63 Hz (C4音) 的正弦波\n",
          "# 2. 生成一个 329.63 Hz (E4音) 的正弦波\n",
          "# 3. 将两个波相加\n",
          "# 4. 画出结果\n",
          "\n",
          "freq_C4 = 261.63   # C4音\n",
          "freq_E4 = 329.63   # E4音\n",
          "\n",
          "# TODO: 生成C4和E4的正弦波\n",
          "wave_C4 = amplitude * np.sin(2 * np.pi * freq_C4 * t)\n",
          "wave_E4 = amplitude * np.sin(2 * np.pi * freq_E4 * t)\n",
          "\n",
          "# TODO: 将两个波相加\n",
          "composite = wave_C4 + wave_E4\n",
          "\n",
          "# 可视化\n",
          "plt.figure(figsize=(12, 4))\n",
          "plt.plot(t[:500], composite[:500])\n",
          "plt.title('Composite Wave (C4 + E4)')\n",
          "plt.xlabel('Time (s)')\n",
          "plt.ylabel('Amplitude')\n",
          "plt.grid(True)\n",
          "plt.show()"]),

    md(["## 4. 控制流：if / for / while\n",
        "\n",
        "### 4.1 if 条件判断\n",
        "\n",
        "在音频处理中，我们经常需要根据条件做不同的处理。"]),

    code(["# 判断频率范围\n",
          "def classify_frequency(freq):\n",
          "    if freq < 300:\n",
          "        return '低频 (Bass)'\n",
          "    elif freq < 1000:\n",
          "        return '中频 (Mid)'\n",
          "    elif freq < 4000:\n",
          "        return '中高频 (Upper Mid)'\n",
          "    else:\n",
          "        return '高频 (Treble)'\n",
          "\n",
          "# 测试\n",
          "test_freqs = [100, 440, 2000, 8000]\n",
          "for f in test_freqs:\n",
          "    print(f'{f} Hz → {classify_frequency(f)}')"]),

    md(["### 4.2 for 循环\n",
        "\n",
        "在音频处理中，for循环最常见的用途是批量处理。"]),

    code(["# 批量生成不同频率的正弦波\n",
          "frequencies = [261.63, 293.66, 329.63, 349.23, 392.00, 440.00, 493.88, 523.25]\n",
          "note_names = ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5']\n",
          "\n",
          "waves = {}  # 用字典存储不同频率的波\n",
          "for freq, name in zip(frequencies, note_names):\n",
          "    wave = amplitude * np.sin(2 * np.pi * freq * t)\n",
          "    waves[name] = wave\n",
          "    print(f'{name} ({freq} Hz): 长度={len(wave)}, 最大值={np.max(np.abs(wave)):.3f}')"]),

    md(["### 4.3 while 循环\n",
        "\n",
        "while循环在音频处理中相对少见，但有些场景（如找到第一个过零点）会用到。"]),

    code(["# 找到波形中第一个过零点的位置\n",
          "i = 0\n",
          "while sine_wave[i] > 0 and i < len(sine_wave) - 1:\n",
          "    i += 1\n",
          "\n",
          "zero_crossing_time = t[i]\n",
          "print(f'第一个过零点出现在 t = {zero_crossing_time:.6f} 秒')\n",
          "print(f'对应样本索引: {i}')\n",
          "print(f'验证: sine_wave[{i-1}] = {sine_wave[i-1]:.6f}, sine_wave[{i}] = {sine_wave[i]:.6f}')"]),

    md(["## 5. 函数——从\"复制粘贴\"到\"函数调用\"\n",
        "\n",
        "**这是本节课最重要的部分。**\n",
        "\n",
        "物理背景的学生最常见的编程坏习惯就是把所有代码写在脚本的最外层，从头到尾执行一遍——没有函数、没有模块化。\n",
        "\n",
        "我们来看一个具体的例子。"]),

    md(["### 5.1 坏习惯：复制粘贴\n",
        "\n",
        "假设你需要生成3个不同频率的正弦波并画图。最直观的做法是："]),

    code(["# ===== 坏习惯：复制粘贴 =====\n",
          "# 生成 440 Hz 的正弦波并画图\n",
          "wave_440 = 0.5 * np.sin(2 * np.pi * 440 * t)\n",
          "plt.figure(figsize=(10, 3))\n",
          "plt.plot(t[:500], wave_440[:500])\n",
          "plt.title('440 Hz Sine Wave')\n",
          "plt.xlabel('Time (s)')\n",
          "plt.ylabel('Amplitude')\n",
          "plt.grid(True)\n",
          "plt.show()\n",
          "\n",
          "# 生成 261 Hz 的正弦波并画图（复制上面的代码，改数字）\n",
          "wave_261 = 0.5 * np.sin(2 * np.pi * 261 * t)\n",
          "plt.figure(figsize=(10, 3))\n",
          "plt.plot(t[:500], wave_261[:500])\n",
          "plt.title('261 Hz Sine Wave')\n",
          "plt.xlabel('Time (s)')\n",
          "plt.ylabel('Amplitude')\n",
          "plt.grid(True)\n",
          "plt.show()\n",
          "\n",
          "# 生成 880 Hz 的正弦波并画图（再复制一次...）\n",
          "wave_880 = 0.5 * np.sin(2 * np.pi * 880 * t)\n",
          "plt.figure(figsize=(10, 3))\n",
          "plt.plot(t[:500], wave_880[:500])\n",
          "plt.title('880 Hz Sine Wave')\n",
          "plt.xlabel('Time (s)')\n",
          "plt.ylabel('Amplitude')\n",
          "plt.grid(True)\n",
          "plt.show()"]),

    md(["### 5.2 好习惯：封装成函数\n",
        "\n",
        "现在把上面的重复代码封装成一个函数："]),

    code(["def plot_sine_wave(freq, amp=0.5, sr=16000, dur=1.0, num_samples=500):\n",
          "    \"\"\"生成正弦波并画图\n",
          "    \n",
          "    参数:\n",
          "        freq: 频率 (Hz)\n",
          "        amp: 振幅 (默认 0.5)\n",
          "        sr: 采样率 (默认 16000 Hz)\n",
          "        dur: 时长 (默认 1.0 秒)\n",
          "        num_samples: 画图时显示的样本数\n",
          "    \"\"\"\n",
          "    t = np.linspace(0, dur, int(sr * dur), endpoint=False)\n",
          "    wave = amp * np.sin(2 * np.pi * freq * t)\n",
          "    \n",
          "    plt.figure(figsize=(10, 3))\n",
          "    plt.plot(t[:num_samples], wave[:num_samples])\n",
          "    plt.title(f'{freq} Hz Sine Wave')\n",
          "    plt.xlabel('Time (s)')\n",
          "    plt.ylabel('Amplitude')\n",
          "    plt.grid(True)\n",
          "    plt.show()\n",
          "    \n",
          "    return wave\n",
          "\n",
          "# 现在只需要一行代码\n",
          "wave_440 = plot_sine_wave(440)\n",
          "wave_261 = plot_sine_wave(261)\n",
          "wave_880 = plot_sine_wave(880)"]),

    md(["### 对比\n",
        "\n",
        "| 方式 | 代码行数 | 如果要改画图参数？ |\n",
        "|------|---------|-------------------|\n",
        "| 复制粘贴 | ~24行 | 需要改3个地方 |\n",
        "| 函数封装 | ~3行 | 只需改函数定义1处 |\n",
        "\n",
        "**函数不只是\"把代码打包\"，而是\"把思路分块\"**——每个函数做一件事，函数名就是这件事的描述。"]),

    md(["### 5.3 函数的参数和返回值\n",
        "\n",
        "函数可以有多个参数和返回值。"]),

    code(["def generate_sine_wave(freq, amp=0.5, sr=16000, dur=1.0):\n",
          "    \"\"\"生成正弦波\n",
          "    \n",
          "    参数:\n",
          "        freq: 频率 (Hz)\n",
          "        amp: 振幅\n",
          "        sr: 采样率\n",
          "        dur: 时长\n",
          "    \n",
          "    返回:\n",
          "        t: 时间轴\n",
          "        wave: 波形数据\n",
          "    \"\"\"\n",
          "    t = np.linspace(0, dur, int(sr * dur), endpoint=False)\n",
          "    wave = amp * np.sin(2 * np.pi * freq * t)\n",
          "    return t, wave\n",
          "\n",
          "# 使用\n",
          "t, wave = generate_sine_wave(440)\n",
          "print(f'波形长度: {len(wave)}')\n",
          "print(f'前5个样本: {wave[:5]}')"]),

    md(["### 练习2：写一个函数\n",
        "\n",
        "**任务**：写一个函数 `generate_composite_wave(freqs, amps, sr=16000, dur=1.0)`，它：\n",
        "1. 接收频率列表 `freqs` 和对应的振幅列表 `amps`\n",
        "2. 生成每个频率对应的正弦波\n",
        "3. 将所有波相加\n",
        "4. 返回时间轴 `t` 和复合波 `composite`\n",
        "\n",
        "**提示**：参考上面 `generate_sine_wave` 函数的写法，用 for 循环遍历 freqs 和 amps。"]),

    code(["# ===== 练习2：写一个函数 =====\n",
          "def generate_composite_wave(freqs, amps, sr=16000, dur=1.0):\n",
          "    \"\"\"生成复合波（多个正弦波叠加）\n",
          "    \n",
          "    参数:\n",
          "        freqs: 频率列表\n",
          "        amps: 对应的振幅列表\n",
          "        sr: 采样率\n",
          "        dur: 时长\n",
          "    \n",
          "    返回:\n",
          "        t: 时间轴\n",
          "        composite: 复合波\n",
          "    \"\"\"\n",
          "    # TODO: 生成时间轴\n",
          "    t = np.linspace(0, dur, int(sr * dur), endpoint=False)\n",
          "    \n",
          "    # TODO: 生成复合波\n",
          "    composite = np.zeros_like(t)\n",
          "    for freq, amp in zip(freqs, amps):\n",
          "        # TODO: 生成每个频率的正弦波并叠加\n",
          "        wave = amp * np.sin(2 * np.pi * freq * t)\n",
          "        composite += wave\n",
          "    \n",
          "    return t, composite\n",
          "\n",
          "# 测试\n",
          "freqs = [261.63, 329.63, 392.00]  # C大三和弦: C4, E4, G4\n",
          "amps = [0.5, 0.5, 0.5]\n",
          "t, chord = generate_composite_wave(freqs, amps)\n",
          "\n",
          "plt.figure(figsize=(12, 4))\n",
          "plt.plot(t[:500], chord[:500])\n",
          "plt.title('C Major Chord (C4 + E4 + G4)')\n",
          "plt.xlabel('Time (s)')\n",
          "plt.ylabel('Amplitude')\n",
          "plt.grid(True)\n",
          "plt.show()"]),

    md(["## 6. 列表与字典\n",
        "\n",
        "在音频处理中，我们经常需要存储和管理音频文件的信息。"]),

    md(["### 6.1 列表\n",
        "\n",
        "列表用于存储有序的数据集合。"]),

    code(["# 常见的音频采样率\n",
          "common_sample_rates = [8000, 16000, 22050, 44100, 48000, 96000]\n",
          "print(f'常见采样率: {common_sample_rates}')\n",
          "print(f'CD音质采样率: {common_sample_rates[3]} Hz')\n",
          "print(f'电话音质采样率: {common_sample_rates[0]} Hz')"]),

    md(["### 6.2 字典\n",
        "\n",
        "字典用于存储键值对，非常适合存储结构化的数据。"]),

    code(["# 用字典存储wav文件的信息\n",
          "audio_info = {\n",
          "    'filename': 'speech.wav',\n",
          "    'sample_rate': 16000,\n",
          "    'duration': 3.5,\n",
          "    'num_channels': 1,\n",
          "    'num_samples': None,  # 稍后计算\n",
          "    'is_speech': True,\n",
          "}\n",
          "\n",
          "# 计算并更新\n",
          "audio_info['num_samples'] = audio_info['sample_rate'] * audio_info['duration']\n",
          "\n",
          "print('音频文件信息:')\n",
          "for key, value in audio_info.items():\n",
          "    print(f'  {key}: {value}')"]),

    md(["### 练习3：用字典管理多个音频文件\n",
        "\n",
        "**任务**：创建一个字典 `audio_files`，其中每个键是文件名，值是另一个字典（包含 sample_rate, duration, is_speech）。然后用 for 循环遍历，打印每个文件的总样本数。"]),

    code(["# ===== 练习3：用字典管理多个音频文件 =====\n",
          "audio_files = {\n",
          "    'speech_clean.wav': {\n",
          "        'sample_rate': 16000,\n",
          "        'duration': 3.5,\n",
          "        'is_speech': True,\n",
          "    },\n",
          "    'speech_noisy.wav': {\n",
          "        'sample_rate': 16000,\n",
          "        'duration': 5.0,\n",
          "        'is_speech': True,\n",
          "    },\n",
          "    'noise_white.wav': {\n",
          "        'sample_rate': 44100,\n",
          "        'duration': 10.0,\n",
          "        'is_speech': False,\n",
          "    },\n",
          "}\n",
          "\n",
          "# TODO: 用 for 循环遍历，打印每个文件的总样本数\n",
          "for filename, info in audio_files.items():\n",
          "    num_samples = int(info['sample_rate'] * info['duration'])\n",
          "    print(f\"{filename}: {num_samples} 样本, 语音={info['is_speech']}\")"]),

    md(["## 7. 综合练习\n",
        "\n",
        "**任务**：写一个函数 `generate_sine_wave(freq, duration, sample_rate, amplitude)`，它：\n",
        "1. 生成指定频率和时长的正弦波\n",
        "2. 返回时间轴 `t` 和波形数据 `wave`\n",
        "3. 画出波形的前500个样本\n",
        "\n",
        "**要求**：不参考上面的代码，独立完成。"]),

    code(["# ===== 综合练习 =====\n",
          "def generate_sine_wave(freq, duration, sample_rate, amplitude):\n",
          "    \"\"\"生成正弦波\n",
          "    \n",
          "    参数:\n",
          "        freq: 频率 (Hz)\n",
          "        duration: 时长 (秒)\n",
          "        sample_rate: 采样率 (Hz)\n",
          "        amplitude: 振幅\n",
          "    \n",
          "    返回:\n",
          "        t: 时间轴\n",
          "        wave: 波形数据\n",
          "    \"\"\"\n",
          "    # TODO: 生成时间轴\n",
          "    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)\n",
          "    \n",
          "    # TODO: 生成正弦波\n",
          "    wave = amplitude * np.sin(2 * np.pi * freq * t)\n",
          "    \n",
          "    # TODO: 画图\n",
          "    plt.figure(figsize=(12, 4))\n",
          "    plt.plot(t[:500], wave[:500])\n",
          "    plt.title(f'{freq} Hz Sine Wave, Amplitude: {amplitude}')\n",
          "    plt.xlabel('Time (s)')\n",
          "    plt.ylabel('Amplitude')\n",
          "    plt.grid(True)\n",
          "    plt.show()\n",
          "    \n",
          "    return t, wave\n",
          "\n",
          "# 测试你的函数\n",
          "t, wave = generate_sine_wave(440, 0.5, 16000, 0.5)"]),

    md(["## 本节要点\n",
        "\n",
        "1. **变量**存储数据，选择有意义的变量名\n",
        "2. **NumPy数组**是音频处理的核心数据结构，学会向量化思维\n",
        "3. **控制流**（if/for/while）用于条件判断和批量处理\n",
        "4. **函数**是最重要的概念——从\"复制粘贴\"到\"函数调用\"，函数把思路分块\n",
        "5. **列表和字典**用于组织和管理数据\n"]),

    md(["---\n",
        "下一节：[02-oop-audio.ipynb](02-oop-audio.ipynb) — 面向对象与代码组织"]),
]

# ============================================================
# Notebook 2: Python进阶——面向对象与代码组织
# ============================================================
nb2_cells = [
    md(["# Python进阶——面向对象与代码组织\n",
        "\n",
        "## 学习目标\n",
        "\n",
        "- 理解从\"函数+字典\"到\"类\"的过渡\n",
        "- 能读懂别人写的类，能写简单的类\n",
        "- 理解继承的概念\n",
        "- 理解模块/包的概念，知道import做了什么\n",
        "- **关键衔接**：读懂PyTorch源码中的类（nn.Module, Dataset）\n"]),

    md(["## 1. 从\"函数+字典\"到\"类\"\n",
        "\n",
        "假设我们要管理一段音频信号，需要：\n",
        "- 存储波形数据、采样率等信息\n",
        "- 提供播放、画图、计算频谱等方法\n",
        "\n",
        "先来看两种不同的实现方式。"]),

    md(["### 1.1 方式一：函数 + 字典\n",
        "\n",
        "数据（字典）和操作（函数）是分开的。"]),

    code(["# ===== 方式一：函数 + 字典 =====\n",
          "\n",
          "def create_signal(waveform, sample_rate, label=''):\n",
          "    \"\"\"创建一个信号字典\"\"\"\n",
          "    return {\n",
          "        'waveform': waveform,\n",
          "        'sample_rate': sample_rate,\n",
          "        'label': label,\n",
          "    }\n",
          "\n",
          "def plot_signal(signal_dict):\n",
          "    \"\"\"画出信号\"\"\"\n",
          "    sr = signal_dict['sample_rate']\n",
          "    t = np.linspace(0, len(signal_dict['waveform'])/sr, len(signal_dict['waveform']), endpoint=False)\n",
          "    plt.figure(figsize=(12, 4))\n",
          "    plt.plot(t, signal_dict['waveform'])\n",
          "    plt.title(signal_dict['label'])\n",
          "    plt.xlabel('Time (s)')\n",
          "    plt.show()\n",
          "\n",
          "def compute_spectrum(signal_dict):\n",
          "    \"\"\"计算频谱\"\"\"\n",
          "    N = len(signal_dict['waveform'])\n",
          "    spectrum = np.abs(np.fft.rfft(signal_dict['waveform']))\n",
          "    freqs = np.fft.rfftfreq(N, 1/signal_dict['sample_rate'])\n",
          "    return freqs, spectrum\n",
          "\n",
          "# 使用\n",
          "t = np.linspace(0, 1, 16000, endpoint=False)\n",
          "wave = 0.5 * np.sin(2 * np.pi * 440 * t)\n",
          "sig = create_signal(wave, 16000, '440 Hz Sine Wave')\n",
          "plot_signal(sig)"]),

    md(["### 1.2 方式二：类\n",
        "\n",
        "现在用类来做同样的事。**数据和方法绑在一起**。"]),

    code(["# ===== 方式二：类 =====\n",
          "\n",
          "class Signal:\n",
          "    \"\"\"音频信号类\"\"\"\n",
          "    \n",
          "    def __init__(self, waveform, sample_rate, label=''):\n",
          "        \"\"\"初始化方法（构造函数）\n",
          "        \n",
          "        self.waveform = waveform    # 波形数据\n",
          "        self.sample_rate = sample_rate  # 采样率\n",
          "        self.label = label          # 标签\n",
          "    \n",
          "    def plot(self):\n",
          "        \"\"\"画出信号\"\"\"\n",
          "        sr = self.sample_rate\n",
          "        t = np.linspace(0, len(self.waveform)/sr, len(self.waveform), endpoint=False)\n",
          "        plt.figure(figsize=(12, 4))\n",
          "        plt.plot(t, self.waveform)\n",
          "        plt.title(self.label)\n",
          "        plt.show()\n",
          "    \n",
          "    def compute_spectrum(self):\n",
          "        \"\"\"计算频谱\"\"\"\n",
          "        N = len(self.waveform)\n",
          "        spectrum = np.abs(np.fft.rfft(self.waveform))\n",
          "        freqs = np.fft.rfftfreq(N, 1/self.sample_rate)\n",
          "        return freqs, spectrum\n",
          "\n",
          "# 使用\n",
          "sig = Signal(wave, 16000, '440 Hz Sine Wave')\n",
          "sig.plot()"]),

    md(["### 对比\n",
        "\n",
        "| 方式 | 调用方式 | 问题 |\n",
        "|------|---------|------|\n",
        "| 函数+字典 | `plot_signal(sig)` | 函数和数据是分开的，需要把字典传给函数 |\n",
        "| 类 | `sig.plot()` | 数据和方法绑在一起，调用更自然 |\n",
        "\n",
        "**类的核心思想**：数据（属性）和操作数据的方法绑在一起。\n",
        "\n",
        "- `self.waveform` 是属性（存储数据）\n",
        "- `self.plot()` 是方法（操作数据）\n",
        "- `self` 就是实例本身\n"]),

    md(["## 2. 继承——在已有的东西上加修改\n",
        "\n",
        "继承是面向对象中最重要的概念之一。它的直觉很简单：\n",
        "\n",
        "> **继承就是在已有的东西上加修改。**\n",
        "\n",
        "比如：\n",
        "- `Signal` 是基类，能存储波形、画图\n",
        "- `SineWave` 继承 `Signal`，但专门生成正弦波\n",
        "- `NoisySignal` 继承 `Signal`，但在初始化时额外加了噪声\n"]),

    code(["class SineWave(Signal):\n",
          "    \"\"\"正弦波信号——继承Signal，专门生成正弦波\"\"\"\n",
          "    \n",
          "    def __init__(self, frequency, amplitude=0.5, duration=1.0, sample_rate=16000):\n",
          "        # 先生成波形\n",
          "        t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)\n",
          "        waveform = amplitude * np.sin(2 * np.pi * frequency * t)\n",
          "        \n",
          "        # 然后调用父类的__init__\n",
          "        super().__init__(waveform, sample_rate, f'{frequency} Hz Sine Wave')\n",
          "        \n",
          "        # 子类可以添加自己的属性\n",
          "        self.frequency = frequency\n",
          "        self.amplitude = amplitude\n",
          "        self.duration = duration\n",
          "\n",
          "# 使用\n",
          "sine = SineWave(440)\n",
          "print(f'频率: {sine.frequency} Hz')\n",
          "print(f'采样率: {sine.sample_rate} Hz')\n",
          "sine.plot()"]),

    code(["class NoisySignal(Signal):\n",
          "    \"\"\"带噪信号——继承Signal，在干净信号上加噪声\"\"\"\n",
          "    \n",
          "    def __init__(self, clean_waveform, sample_rate, noise_level=0.1, label=''):\n",
          "        # 在干净信号上加高斯噪声\n",
          "        noise = np.random.randn(len(clean_waveform)) * noise_level\n",
          "        noisy = clean_waveform + noise\n",
          "        \n",
          "        # 调用父类构造函数\n",
          "        label = label or f'Noisy Signal (noise_level={noise_level})'\n",
          "        super().__init__(noisy, sample_rate, label)\n",
          "        \n",
          "        # 子类自己的属性\n",
          "        self.clean_waveform = clean_waveform\n",
          "        self.noise_level = noise_level\n",
          "    \n",
          "    def compute_snr(self):\n",
          "        \"\"\"计算信噪比 (dB)\"\"\"\n",
          "        signal_power = np.mean(self.clean_waveform ** 2)\n",
          "        noise = self.waveform - self.clean_waveform\n",
          "        noise_power = np.mean(noise ** 2)\n",
          "        if noise_power == 0:\n",
          "            return float('inf')\n",
          "        return 10 * np.log10(signal_power / noise_power)\n",
          "\n",
          "# 使用\n",
          "clean = SineWave(440)\n",
          "noisy = NoisySignal(clean.waveform, clean.sample_rate, noise_level=0.3)\n",
          "print(f'SNR: {noisy.compute_snr():.1f} dB')\n",
          "noisy.plot()"]),

    md(["## 3. 为什么PyTorch里全是类？\n",
        "\n",
        "现在你有了理解PyTorch代码的基础。PyTorch中的所有组件都是类：\n",
        "\n",
        "- `nn.Module` 是所有神经网络层的基类\n",
        "- `nn.Linear` 继承 `nn.Module`，实现了线性变换\n",
        "- `nn.Conv2d` 继承 `nn.Module`，实现了2D卷积\n",
        "\n",
        "让我们打开PyTorch源码看看。"]),

    code(["# 查看nn.Module的源码\n",
          "import inspect\n",
          "import torch.nn as nn\n",
          "\n",
          "# 只看__init__和forward方法\n",
          "source = inspect.getsource(nn.Module)\n",
          "# 打印前30行\n",
          "for i, line in enumerate(source.split('\\n')[:30], 1):\n",
          "    print(f'{i:3d}: {line}')"]),

    md(["### 关键理解\n",
        "\n",
        "1. `nn.Module` 的 `__init__` 方法里注册子模块和参数\n",
        "2. `forward` 方法定义了数据如何流过网络\n",
        "3. 你不需要自己写 `backward`——PyTorch的自动微分系统帮你做了\n",
        "4. 所有自定义的网络层都继承 `nn.Module`，只需实现 `__init__` 和 `forward`\n"]),

    code(["# 一个最简单的nn.Module示例\n",
          "import torch\n",
          "import torch.nn as nn\n",
          "\n",
          "class SimpleLinear(nn.Module):\n",
          "    \"\"\"最简单的神经网络层：线性变换 y = Wx + b\"\"\"\n",
          "    \n",
          "    def __init__(self, in_features, out_features):\n",
          "        # 第一步：调用父类的__init__\n",
          "        super().__init__()\n",
          "        \n",
          "        # 第二步：在__init__中定义层\n",
          "        self.linear = nn.Linear(in_features, out_features)\n",
          "    \n",
          "    def forward(self, x):\n",
          "        # forward定义数据如何流过网络\n",
          "        return self.linear(x)\n",
          "\n",
          "# 使用\n",
          "layer = SimpleLinear(3, 2)\n",
          "x = torch.randn(5, 3)  # batch_size=5, in_features=3\n",
          "y = layer(x)\n",
          "print(f'输入形状: {x.shape}')\n",
          "print(f'输出形状: {y.shape}')"]),

    md(["### nn.Module vs 普通类：有什么区别？\n",
        "\n",
        "| 特性 | 普通类 | nn.Module |\n",
        "|------|--------|----------|\n",
        "| 参数管理 | 手动管理 | `parameters()` 自动收集 |\n",
        "| GPU转移 | 手动 `.to('cuda')` | 所有子模块自动转移 |\n",
        "| 保存加载 | 手动pickle | `state_dict()` 自动处理 |\n",
        "| 梯度计算 | 手动 | 自动（`autograd`） |\n",
        "\n",
        "**核心**：`nn.Module` 帮你管理了神经网络中所有繁琐的工程细节，让你只需关注 `__init__`（定义层）和 `forward`（定义数据流）。"]),

    md(["## 4. 模块与包：从notebook到.py文件\n",
        "\n",
        "在研究中，我们经常需要把notebook中的代码整理成可复用的模块。\n",
        "\n",
        "### 4.1 为什么需要模块？\n",
        "\n",
        "- notebook适合探索和可视化\n",
        "- 当代码需要在多个实验中复用时，需要抽取到.py文件\n",
        "- PyTorch的Dataset、模型定义等，通常放在单独的.py文件中"]),

    code(["# 演示：import一个模块\n",
          "import os\n",
          "\n",
          "# 假设我们有一个文件 utils/signal_utils.py\n",
          "# 其中定义了 Signal 类\n",
          "#\n",
          "# utils/\n",
          "# ├── __init__.py\n",
          "# └── signal_utils.py\n",
          "#\n",
          "# 在其他文件中可以这样使用：\n",
          "# from utils.signal_utils import Signal\n",
          "# from utils.signal_utils import SineWave\n",
          "\n",
          "print('模块导入演示完成')"]),

    md(["### 4.2 import做了什么？\n",
        "\n",
        "```python\n",
        "from utils.signal_utils import Signal\n",
        "```\n",
        "\n",
        "这行代码做了三件事：\n",
        "1. 找到 `utils/signal_utils.py` 文件\n",
        "2. 执行文件中的所有代码\n",
        "3. 把 `Signal` 类引入当前命名空间\n",
        "\n",
        "这就是为什么 `__init__.py` 很重要——它告诉Python这个目录是一个包。"]),

    md(["## 5. 实战：读懂PyTorch Dataset源码\n",
        "\n",
        "PyTorch的 `Dataset` 类是深度学习数据加载的基础。让我们看看它的源码。"]),

    code(["# 查看Dataset的源码\n",
          "from torch.utils.data import Dataset\n",
          "import inspect\n",
          "\n",
          "source = inspect.getsource(Dataset)\n",
          "print(source)"]),

    md(["源码非常简单——只有3个方法：\n",
        "\n",
        "1. `__getitem__`：根据索引返回一个样本\n",
        "2. `__len__`：返回数据集的大小\n",
        "3. `__init__`：初始化（抽象方法，子类必须实现）\n",
        "\n",
        "这就是PyTorch数据加载的基石！你只需要实现这三个方法，`DataLoader` 就会自动处理批量加载、数据打乱、多进程加载等所有细节。"]),

    md(["## 6. 编程练习：写一个AudioDataset类\n",
        "\n",
        "**任务**：写一个 `AudioDataset` 类，继承 `Dataset`，实现：\n",
        "1. `__init__`：接收文件列表和标签列表\n",
        "2. `__len__`：返回数据集大小\n",
        "3. `__getitem__`：根据索引加载音频文件并返回（波形, 标签）\n",
        "\n",
        "**这是模块3中Dataset/DataLoader的前置练习**。"]),

    code(["import torch\n",
          "from torch.utils.data import Dataset, DataLoader\n",
          "import numpy as np\n",
          "import soundfile as sf\n",
          "import os\n",
          "\n",
          "class AudioDataset(Dataset):\n",
          "    \"\"\"音频数据集\n",
          "    \n",
          "    参数:\n",
          "        file_list: 音频文件路径列表\n",
          "        label_list: 对应的标签列表\n",
          "        sample_rate: 目标采样率（如果需要重采样）\n",
          "    \"\"\"\n",
          "    \n",
          "    def __init__(self, file_list, label_list, sample_rate=16000):\n",
          "        # TODO: 验证输入\n",
          "        assert len(file_list) == len(label_list)\n",
          "        \n",
          "        # TODO: 保存属性\n",
          "        self.file_list = file_list\n",
          "        self.label_list = label_list\n",
          "        self.sample_rate = sample_rate\n",
          "    \n",
          "    def __len__(self):\n",
          "        # TODO: 返回数据集大小\n",
          "        return len(self.file_list)\n",
          "    \n",
          "    def __getitem__(self, idx):\n",
          "        # TODO: 根据索引获取文件路径和标签\n",
          "        filepath = self.file_list[idx]\n",
          "        label = self.label_list[idx]\n",
          "        \n",
          "        # TODO: 加载音频文件\n",
          "        waveform, sr = sf.read(filepath)\n",
          "        \n",
          "        # TODO: 转为torch张量\n",
          "        waveform_tensor = torch.FloatTensor(waveform)\n",
          "        label_tensor = torch.LongTensor([label])[0]\n",
          "        \n",
          "        return waveform_tensor, label_tensor\n",
          "\n",
          "# 演示使用方式（不需要真实文件）\n",
          "print('AudioDataset类定义完成')\n",
          "print(f'类继承关系: {AudioDataset.__mro__}')"]),

    md(["### DataLoader的使用\n",
        "\n",
        "有了Dataset，DataLoader会自动处理：\n",
        "- 批量加载（batch_size）\n",
        "- 数据打乱（shuffle）\n",
        "- 多进程加载（num_workers）\n",
        "- 自动填充（collate_fn）"]),

    code(["# DataLoader使用演示\n",
          "from torch.utils.data import DataLoader, TensorDataset\n",
          "\n",
          "# 用TensorDataset做简单演示（不需要真实音频文件）\n",
          "dummy_data = torch.randn(100, 16000)  # 100个样本，每个16000个采样点\n",
          "dummy_labels = torch.randint(0, 10, (100,))  # 100个标签，10个类别\n",
          "\n",
          "dataset = TensorDataset(dummy_data, dummy_labels)\n",
          "loader = DataLoader(dataset, batch_size=16, shuffle=True)\n",
          "\n",
          "for batch_x, batch_y in loader:\n",
          "    print(f'批量数据形状: {batch_x.shape}')  # [16, 16000]\n",
          "    print(f'批量标签形状: {batch_y.shape}')  # [16]\n",
          "    break"]),

    md(["## 本节要点\n",
        "\n",
        "1. **类 = 数据 + 方法**，属性（self.xxx）存储数据，方法操作数据\n",
        "2. **继承**就是在父类的基础上加修改，用 `super().__init__()` 调用父类构造函数\n",
        "3. **nn.Module** 是PyTorch的基石——只需实现 `__init__`（定义层）和 `forward`（定义数据流）\n",
        "4. **Dataset** 只需实现 `__len__` 和 `__getitem__`，DataLoader自动处理批量、打乱等细节\n"]),

    md(["---\n",
        "下一节：[03-debugging-git.ipynb](03-debugging-git.ipynb) — 调试、版本控制与编程习惯"]),
]

# ============================================================
# Notebook 3: 调试、版本控制与编程习惯
# ============================================================
nb3_cells = [
    md(["# 调试、版本控制与编程习惯\n",
        "\n",
        "## 学习目标\n",
        "\n",
        "- 掌握基本的调试方法（print → pdb → Jupyter调试器）\n",
        "- 学会读懂常见Python报错信息\n",
        "- 掌握Git基本操作（init, add, commit, push, pull）\n",
        "- 建立良好的编程习惯（命名规范、注释、格式化）\n"]),

    md(["## 1. 调试方法\n",
        "\n",
        "调试是编程能力中最被忽视的，也是提升编程自信最有效的。\n",
        "\n",
        "物理背景学生遇到报错时最常见的反应是\"代码报错了\"然后等待救援，而不是自己读报错信息、定位问题。\n",
        "\n",
        "**目标**：建立\"报错是朋友不是敌人\"的心态——报错信息就是在告诉你哪里出了问题，学会读它就能解决大部分问题。"]),

    md(["### 1.1 最常见的报错类型\n",
        "\n",
        "在深度学习/音频处理中，最常遇到的报错："]),

    code(["# ====== 故意制造报错，学习读报错 ======\n",
          "\n",
          "# 1. IndexError: 索引越界\n",
          "lst = [1, 2, 3]\n",
          "try:\n",
          "    lst[5]\n",
          "except IndexError as e:\n",
          "    print(f'IndexError: {e}')"]),

    code(["# 2. KeyError: 字典键不存在\n",
          "d = {'a': 1, 'b': 2}\n",
          "try:\n",
          "    d['c']\n",
          "except KeyError as e:\n",
          "    print(f'KeyError: {e}')"]),

    code(["# 3. ValueError: 值错误\n",
          "try:\n",
          "    int('hello')\n",
          "except ValueError as e:\n",
          "    print(f'ValueError: {e}')"]),

    code(["# 4. TypeError: 类型错误\n",
          "try:\n",
          "    '2' + 2\n",
          "except TypeError as e:\n",
          "    print(f'TypeError: {e}')"]),

    code(["# 5. RuntimeError: 运行时错误（PyTorch中最常见）\n",
          "# 最典型的：维度不匹配\n",
          "import torch\n",
          "import torch.nn as nn\n",
          "\n",
          "linear = nn.Linear(10, 5)  # 期望输入维度为10\n",
          "x = torch.randn(3, 8)      # 实际输入维度为8\n",
          "try:\n",
          "    y = linear(x)\n",
          "except RuntimeError as e:\n",
          "    print(f'RuntimeError: {e}')\n",
          "    print()\n",
          "    print('关键信息解读:')\n",
          "    print('  - Mat1和Mat2维度不匹配')\n",
          "    print('  - 最后一维: 8 vs 10')\n",
          "    print('  - 意思是: 输入x的最后一个维度是8，但线性层期望10')\n",
          "    print('  - 解决: 检查x.shape，确认最后一维是否正确')"]),

    md(["### 报错信息阅读技巧\n",
        "\n",
        "1. **从下往上读**——最后一行是错误类型和消息，最有信息量\n",
        "2. **看Traceback**——它告诉你错误发生在哪一行、调用链是什么\n",
        "3. **读最后一行两遍**——第一遍理解大意，第二遍找关键数字\n",
        "4. **维度不匹配是最常见的错误**——养成习惯：每步都 `print(tensor.shape)`"]),

    md(["### 1.2 调试方法演进\n",
        "\n",
        "| 方法 | 优点 | 缺点 |\n",
        "|------|------|------|\n",
        "| print | 最简单 | 需要手动添加/删除 |\n",
        "| pdb | 不需要改代码 | 交互式命令行，不太直观 |\n",
        "| Jupyter调试器 | 可视化断点 | 只在notebook中有效 |\n",
        "| VS Code调试器 | 最专业 | 需要配置 |\n",
        "\n",
        "**建议**：在日常开发中，`print(tensor.shape)` 仍然是最快最实用的调试方法。"]),

    code(["# print调试示例：跟踪张量形状变化\n",
          "import torch\n",
          "import torch.nn as nn\n",
          "\n",
          "class DebugCNN(nn.Module):\n",
          "    def __init__(self):\n",
          "        super().__init__()\n",
          "        self.conv1 = nn.Conv2d(1, 16, 3, padding=1)  # 输入1通道，输出16通道\n",
          "        self.conv2 = nn.Conv2d(16, 32, 3, padding=1)  # 16→32\n",
          "        self.pool = nn.MaxPool2d(2, 2)  # 尺寸减半\n",
          "        self.fc = nn.Linear(32 * 8 * 8, 10)  # 全连接层\n",
          "    \n",
          "    def forward(self, x):\n",
          "        # 每一步都打印形状\n",
          "        print(f'输入: {x.shape}')\n",
          "        \n",
          "        x = self.pool(torch.relu(self.conv1(x)))\n",
          "        print(f'conv1 + pool: {x.shape}')\n",
          "        \n",
          "        x = self.pool(torch.relu(self.conv2(x)))\n",
          "        print(f'conv2 + pool: {x.shape}')\n",
          "        \n",
          "        x = x.view(x.size(0), -1)  # 展平\n",
          "        print(f'flatten: {x.shape}')\n",
          "        \n",
          "        x = self.fc(x)\n",
          "        print(f'fc输出: {x.shape}')\n",
          "        return x\n",
          "\n",
          "# 测试\n",
          "model = DebugCNN()\n",
          "x = torch.randn(4, 1, 32, 32)  # batch=4, channel=1, 32x32\n",
          "y = model(x)"]),

    md(["## 2. Git基础\n",
        "\n",
        "Git是版本管理工具，在研究中它的作用是：\n",
        "\n",
        "- **保存进度**：每次实验结果有改进就commit，随时可以回退\n",
        "- **同步代码**：在服务器和笔记本之间同步\n",
        "- **记录实验**：commit message就是实验记录\n"]),

    code(["# Git基本操作（在终端中执行，这里只展示命令）\n",
          "\n",
          "# 初始化仓库\n",
          "# git init\n",
          "\n",
          "# 添加文件到暂存区\n",
          "# git add .\n",
          "\n",
          "# 提交（相当于保存进度）\n",
          "# git commit -m \"完成模块0的练习\"\n",
          "\n",
          "# 查看当前状态\n",
          "# git status\n",
          "\n",
          "# 查看历史\n",
          "# git log --oneline\n",
          "\n",
          "# 回退到之前的版本\n",
          "# git checkout <commit-hash>\n",
          "\n",
          "print('Git命令参考已就绪')"]),

    md(["### Git commit message 规范\n",
        "\n",
        "好的commit message就是实验记录：\n",
        "\n",
        "```bash\n",
        "# 好的例子\n",
        "git commit -m \"CNN分类器：2层conv+1层fc，准确率85%\"\n",
        "git commit -m \"修改学习率：0.001→0.0001，loss下降更快\"\n",
        "git commit -m \"增加数据增强：随机裁剪+频谱掩蔽，过拟合缓解\"\n",
        "\n",
        "# 坏的例子\n",
        "git commit -m \"update\"\n",
        "git commit -m \"fix bug\"\n",
        "git commit -m \"修改了一下\"\n",
        "```\n",
        "\n",
        "**原则**：commit message要回答\"这次改动做了什么，效果如何？\""]),

    md(["## 3. 编程习惯\n",
        "\n",
        "### 3.1 命名规范\n",
        "\n",
        "| 类型 | 规范 | 例子 |\n",
        "|------|------|------|\n",
        "| 变量/函数 | snake_case | `sample_rate`, `compute_spectrum()` |\n",
        "| 类 | PascalCase | `AudioDataset`, `CNNClassifier` |\n",
        "| 常量 | UPPER_CASE | `SAMPLE_RATE`, `NUM_CLASSES` |\n",
        "| 私有属性 | _前缀 | `self._internal_state` |"]),

    md(["### 3.2 好名字 vs 坏名字\n",
        "\n",
        "**变量名要回答\"这个变量存储什么\"，而不是\"这个变量的类型是什么\"。**"]),

    code(["# ====== 坏名字 vs 好名字 ======\n",
          "\n",
          "# 坏名字\n",
          "a = 16000          # 什么采样率？\n",
          "b = 0.5            # 什么的振幅？\n",
          "c = np.zeros(100)  # 什么的缓冲区？\n",
          "tmp = wave[:500]   # 什么的临时变量？\n",
          "\n",
          "# 好名字\n",
          "sample_rate = 16000\n",
          "amplitude = 0.5\n",
          "output_buffer = np.zeros(100)\n",
          "first_500_samples = wave[:500]"]),

    md(["### 3.3 注释写法\n",
        "\n",
        "**注释要解释\"为什么\"，而不是\"做了什么\"**——代码本身已经说明了\"做了什么\"。"]),

    code(["# ====== 坏注释 vs 好注释 ======\n",
          "\n",
          "# 坏注释：重复代码\n",
          "sr = 16000  # 设置采样率为16000\n",
          "n = int(sr * dur)  # 计算样本数\n",
          "\n",
          "# 好注释：解释\"为什么\"\n",
          "sample_rate = 16000  # CI语音处理的常用采样率\n",
          "num_samples = int(sample_rate * duration)  # int()截断而非四舍五入，避免最后一个样本溢出"]),

    md(["### 3.4 代码格式化\n",
        "\n",
        "使用 `black` 自动格式化代码，不再为格式争论浪费时间。"]),

    code(["# 安装black（在终端中执行）\n",
          "# pip install black\n",
          "\n",
          "# 使用black格式化当前notebook\n",
          "# black notebook.ipynb\n",
          "# 或者格式化整个项目\n",
          "# black .\n",
          "\n",
          "print('代码格式化工具介绍完毕')"]),

    md(["## 4. 综合练习\n",
        "\n",
        "**任务**：将前两次课的代码重构为模块化的项目，提交到Git仓库。\n",
        "\n",
        "### 步骤\n",
        "\n",
        "1. 创建项目目录结构：\n",
        "   ```\n",
        "   audio_tools/\n",
        "   ├── __init__.py\n",
        "   ├── signal.py          # Signal类\n",
        "   ├── generators.py      # SineWave, NoisySignal\n",
        "   └── visualization.py   # 画图工具函数\n",
        "   ```\n",
        "2. 将notebook中的代码整理到对应的.py文件中\n",
        "3. 在notebook中用import引用自己的模块\n",
        "4. 用Git提交，commit message写清楚\n"]),

    code(["# ====== 综合练习：模块化重构 ======\n",
          "\n",
          "# 步骤1：创建目录结构\n",
          "import os\n",
          "\n",
          "project_dir = 'audio_tools'\n",
          "os.makedirs(project_dir, exist_ok=True)\n",
          "\n",
          "# 创建__init__.py（让Python识别这个目录为包）\n",
          "with open(os.path.join(project_dir, '__init__.py'), 'w') as f:\n",
          "    f.write('')\n",
          "\n",
          "print(f'项目目录 {project_dir} 创建完成')"]),

    code(["# 步骤2：将Signal类写入signal.py\n",
          "signal_code = '''\n",
          "import numpy as np\n",
          "import matplotlib.pyplot as plt\n",
          "\n",
          "class Signal:\n",
          "    \"\"\"音频信号基类\"\"\"\n",
          "    \n",
          "    def __init__(self, waveform, sample_rate, label=''):\n",
          "        self.waveform = waveform\n",
          "        self.sample_rate = sample_rate\n",
          "        self.label = label\n",
          "    \n",
          "    def plot(self):\n",
          "        sr = self.sample_rate\n",
          "        t = np.linspace(0, len(self.waveform)/sr, len(self.waveform), endpoint=False)\n",
          "        plt.figure(figsize=(12, 4))\n",
          "        plt.plot(t, self.waveform)\n",
          "        plt.title(self.label)\n",
          "        plt.show()\n",
          "    \n",
          "    def compute_spectrum(self):\n",
          "        N = len(self.waveform)\n",
          "        spectrum = np.abs(np.fft.rfft(self.waveform))\n",
          "        freqs = np.fft.rfftfreq(N, 1/self.sample_rate)\n",
          "        return freqs, spectrum\n",
          "'''\n",
          "\n",
          "with open(os.path.join(project_dir, 'signal.py'), 'w') as f:\n",
          "    f.write(signal_code)\n",
          "print('signal.py 写入完成')"]),

    code(["# 步骤2b：将SineWave和NoisySignal写入generators.py\n",
          "generators_code = '''\n",
          "import numpy as np\n",
          "from .signal import Signal\n",
          "\n",
          "class SineWave(Signal):\n",
          "    \"\"\"正弦波信号\"\"\"\n",
          "    \n",
          "    def __init__(self, frequency, amplitude=0.5, duration=1.0, sample_rate=16000):\n",
          "        t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)\n",
          "        waveform = amplitude * np.sin(2 * np.pi * frequency * t)\n",
          "        label = f'{frequency} Hz Sine Wave'\n",
          "        super().__init__(waveform, sample_rate, label)\n",
          "        self.frequency = frequency\n",
          "        self.amplitude = amplitude\n",
          "        self.duration = duration\n",
          "\n",
          "class NoisySignal(Signal):\n",
          "    \"\"\"带噪信号\"\"\"\n",
          "    \n",
          "    def __init__(self, clean_waveform, sample_rate, noise_level=0.1, label=''):\n",
          "        noise = np.random.randn(len(clean_waveform)) * noise_level\n",
          "        noisy = clean_waveform + noise\n",
          "        label = label or f'Noisy Signal (noise_level={noise_level})'\n",
          "        super().__init__(noisy, sample_rate, label)\n",
          "        self.clean_waveform = clean_waveform\n",
          "        self.noise_level = noise_level\n",
          "    \n",
          "    def compute_snr(self):\n",
          "        signal_power = np.mean(self.clean_waveform ** 2)\n",
          "        noise = self.waveform - self.clean_waveform\n",
          "        noise_power = np.mean(noise ** 2)\n",
          "        if noise_power == 0:\n",
          "            return float('inf')\n",
          "        return 10 * np.log10(signal_power / noise_power)\n",
          "'''\n",
          "\n",
          "with open(os.path.join(project_dir, 'generators.py'), 'w') as f:\n",
          "    f.write(generators_code)\n",
          "print('generators.py 写入完成')"]),

    code(["# 步骤3：测试从模块导入\n",
          "from audio_tools.signal import Signal\n",
          "from audio_tools.generators import SineWave, NoisySignal\n",
          "\n",
          "# 使用方式和之前完全一样\n",
          "sine = SineWave(440)\n",
          "print(f'频率: {sine.frequency} Hz')\n",
          "print(f'采样率: {sine.sample_rate} Hz')\n",
          "\n",
          "clean = SineWave(440)\n",
          "noisy = NoisySignal(clean.waveform, clean.sample_rate, noise_level=0.3)\n",
          "print(f'SNR: {noisy.compute_snr():.1f} dB')"]),

    md(["## 本节要点\n",
        "\n",
        "1. **读报错信息**：从下往上读，最后一行最有信息量；维度不匹配是最常见的bug\n",
        "2. **调试方法**：`print(tensor.shape)` 是最快最实用的；Jupyter调试器和VS Code调试器更专业\n",
        "3. **Git**：`init → add → commit` 是最基本的工作流；commit message要写清楚\n",
        "4. **编程习惯**：好名字回答\"存储什么\"；注释解释\"为什么\"；用black自动格式化\n"]),

    md(["---\n",
        "返回目录：[README.md](../README.md)"]),
]

# Write all notebooks
write_notebook("01-basics-signal.ipynb", nb1_cells)
write_notebook("02-oop-audio.ipynb", nb2_cells)
write_notebook("03-debugging-git.ipynb", nb3_cells)

print("\n所有notebook生成完成！")
