#!/usr/bin/env python3
"""生成模块1的全部Jupyter notebook"""
import json
import os

NOTEBOOK_DIR = os.path.dirname(os.path.abspath(__file__))

def make_notebook(cells):
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "cells": cells
    }

def md(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source if isinstance(source, list) else [source]
    }

def code(source):
    return {
        "cell_type": "code",
        "metadata": {},
        "source": source if isinstance(source, list) else [source],
        "execution_count": None,
        "outputs": []
    }

def shell(source):
    """Shell命令cell，使用!前缀在Jupyter中执行"""
    return {
        "cell_type": "code",
        "metadata": {},
        "source": source if isinstance(source, list) else [source],
        "execution_count": None,
        "outputs": []
    }

def write_notebook(filename, cells):
    nb = make_notebook(cells)
    path = os.path.join(NOTEBOOK_DIR, filename)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)
    print(f"Written: {path}")


# ============================================================
# Notebook 1: Linux生存指南
# ============================================================
nb1_cells = [
    md(["# Linux生存指南\n",
        "\n",
        "## 学习目标\n",
        "\n",
        "- 在Linux终端下完成基本的文件操作\n",
        "- 理解文件权限和管道\n",
        "- 通过SSH远程连接服务器\n",
        "- 使用tmux让程序在后台运行\n",
        "- 能在服务器上找到、查看、操作音频文件\n",
        "\n",
        "## 本节说明\n",
        "\n",
        "本notebook中的shell命令可以通过 `!` 前缀在Jupyter中执行。\n",
        "但**实际使用时，你应该在真正的终端中操作**，而不是在notebook中。\n",
        "notebook中的 `!` 只是用于课堂演示和练习验证。\n"]),

    md(["## 1. 为什么要用Linux？\n",
        "\n",
        "在深度学习研究中，你几乎必然会使用Linux服务器。原因很简单：\n",
        "\n",
        "- **GPU服务器几乎都运行Linux**——Windows和macOS对GPU的支持远不如Linux\n",
        "- **深度学习框架（PyTorch、TensorFlow）在Linux上最稳定**——文档、社区、教程都以Linux为主\n",
        "- **服务器是共享资源**——多人同时使用一台GPU服务器，Linux天然支持多用户\n",
        "- **CI/助听器研究的计算需求**——训练模型、处理数据都需要大量计算\n",
        "\n",
        "**类比**：你的笔记本是工作站，服务器是工厂。你在工作站上设计，去工厂里生产。\n"]),

    md(["## 2. 文件系统与基本命令\n",
        "\n",
        "### 2.1 我在哪里？——pwd 和 ls\n",
        "\n",
        "最常打的两个命令：`pwd`（我在哪里）和 `ls`（这里有什么）。\n"]),

    shell("!pwd  # 显示当前工作目录"),

    shell("!ls   # 列出当前目录的内容"),

    shell("!ls -la  # 列出详细信息（权限、大小、修改时间）"),

    md(["### 2.2 去哪里？——cd\n",
        "\n",
        "```bash\n",
        "cd /home/user          # 绝对路径：从根目录开始\n",
        "cd data                # 相对路径：从当前目录开始\n",
        "cd ..                  # 返回上一级\n",
        "cd ~                   # 回到home目录\n",
        "cd -                   # 回到上次所在的目录\n",
        "```\n"]),

    md(["### 2.3 创建和删除——mkdir, rm, cp, mv\n",
        "\n",
        "```bash\n",
        "# 创建\n",
        "mkdir project           # 创建目录\n",
        "mkdir -p project/data  # 递归创建（父目录不存在也行）\n",
        "\n",
        "# 复制\n",
        "cp file.txt backup/     # 复制文件到目录\n",
        "cp -r data/ backup/     # 递归复制目录\n",
        "\n",
        "# 移动/重命名\n",
        "mv old.txt new.txt      # 重命名\n",
        "mv file.txt data/       # 移动到目录\n",
        "\n",
        "# 删除（⚠️ 慎用！）\n",
        "rm file.txt             # 删除文件（不可恢复！）\n",
        "rm -r directory/        # 递归删除目录\n",
        "rm -ri directory/       # 递归删除，逐个确认\n",
        "```\n",
        "\n",
        "**重要提醒**：`rm` 删除的文件不会进回收站，删了就没了。养成习惯：删除前先 `ls` 确认。"]),

    md(["### 2.4 查看文件——cat, less, head, tail\n",
        "\n",
        "```bash\n",
        "cat file.txt           # 查看整个文件\n",
        "head -20 file.txt     # 查看前20行\n",
        "tail -20 file.txt     # 查看后20行\n",
        "less file.txt         # 分页查看（按q退出）\n",
        "```\n"]),

    md(["### 练习1：文件操作\n",
        "\n",
        "在终端中完成以下操作（不要在notebook中做）：\n",
        "\n",
        "1. 用 `pwd` 确认你当前在哪个目录\n",
        "2. 用 `mkdir` 创建一个目录 `~/lab-training/module1-exercise`\n",
        "3. 用 `cd` 进入这个目录\n",
        "4. 用 `touch` 创建一个文件 `test.txt`\n",
        "5. 用 `cp` 把 `test.txt` 复制为 `test_backup.txt`\n",
        "6. 用 `ls -la` 确认两个文件都存在\n",
        "7. 用 `rm` 删除 `test_backup.txt`\n",
        "8. 用 `ls` 确认只剩 `test.txt`"]),

    md(["## 3. 权限、管道、重定向\n",
        "\n",
        "### 3.1 文件权限\n",
        "\n",
        "Linux中每个文件都有三组权限：所有者(user)、组(group)、其他人(others)。\n"]),

    shell("!ls -la / | head -5  # 看看根目录下的权限格式"),

    md(["权限格式：`-rwxr-xr-x`\n",
        "\n",
        "- 第1位：文件类型（`-`=文件，`d`=目录，`l`=链接）\n",
        "- 第2-4位：所有者权限（r=读，w=写，x=执行）\n",
        "- 第5-7位：组权限\n",
        "- 第8-10位：其他人权限\n",
        "\n",
        "```bash\n",
        "chmod +x script.sh      # 给脚本添加执行权限\n",
        "chmod 755 script.sh     # 用数字设置权限：7=rwx, 5=r-x\n",
        "chmod 644 data.txt      # 常用权限：文件644，目录755\n",
        "```\n"]),

    md(["### 3.2 管道（Pipe）——把命令串起来\n",
        "\n",
        "管道 `|` 把一个命令的输出传给下一个命令。这是Linux最强大的特性之一。\n"]),

    shell(["# 示例：找出当前目录下所有的Python文件\n",
           "!find . -name '*.py' 2>/dev/null | head -5"]),

    shell(["# 示例：统计一个文件有多少行\n",
           "!echo -e 'line1\\nline2\\nline3\\nline4\\nline5' | wc -l"]),

    md(["### 3.3 重定向——保存输出\n",
        "\n",
        "```bash\n",
        "# 把输出保存到文件\n",
        "python train.py > train.log 2>&1    # 标准输出和错误都保存\n",
        "python train.py >> train.log 2>&1   # 追加模式\n",
        "\n",
        "# 只保存错误输出\n",
        "python train.py 2> error.log\n",
        "```\n"]),

    md(["### 3.4 在音频处理中的实际应用\n",
        "\n",
        "```bash\n",
        "# 找出目录下所有wav文件\n",
        "find /data -name '*.wav' | wc -l\n",
        "\n",
        "# 找出采样率为16kHz的wav文件\n",
        "find /data -name '*.wav' -exec soxi {} \\; | grep '16000'\n",
        "\n",
        "# 批量转换采样率\n",
        "for f in *.wav; do sox \"$f\" -r 16000 \"resampled/$f\"; done\n",
        "\n",
        "# 查看GPU使用情况并排序\n",
        "nvidia-smi | grep python\n",
        "```"]),

    md(["### 练习2：管道与重定向\n",
        "\n",
        "1. 用 `find` 找出当前目录下所有的 `.ipynb` 文件\n",
        "2. 用管道把结果传给 `wc -l` 统计数量\n",
        "3. 用 `grep` 在一个文件中搜索关键词\n",
        "4. 把搜索结果重定向到一个新文件中"]),

    md(["## 4. SSH远程连接\n",
        "\n",
        "### 4.1 基本连接\n",
        "\n",
        "```bash\n",
        "# 基本连接\n",
        "ssh username@server_ip\n",
        "\n",
        "# 指定端口\n",
        "ssh -p 2222 username@server_ip\n",
        "\n",
        "# 使用密钥连接（更安全）\n",
        "ssh -i ~/.ssh/my_key username@server_ip\n",
        "```\n",
        "\n",
        "### 4.2 文件传输\n",
        "\n",
        "```bash\n",
        "# 上传文件到服务器\n",
        "scp local_file.txt username@server_ip:~/remote_dir/\n",
        "\n",
        "# 从服务器下载文件\n",
        "scp username@server_ip:~/remote_file.txt ./local_dir/\n",
        "\n",
        "# 传输整个目录\n",
        "scp -r local_dir/ username@server_ip:~/remote_dir/\n",
        "```\n",
        "\n",
        "### 4.3 SSH配置文件\n",
        "\n",
        "编辑 `~/.ssh/config` 可以简化连接：\n",
        "\n",
        "```\n",
        "Host gpu-server\n",
        "    HostName 192.168.1.100\n",
        "    User myname\n",
        "    Port 22\n",
        "    IdentityFile ~/.ssh/my_key\n",
        "```\n",
        "\n",
        "配置之后只需 `ssh gpu-server` 即可连接。\n"]),

    md(["### 练习3：连接服务器\n",
        "\n",
        "1. 用SSH连接到租用的服务器\n",
        "2. 连接后运行 `hostname` 和 `whoami` 确认身份\n",
        "3. 运行 `nvidia-smi` 查看GPU信息\n",
        "4. 用 `scp` 从本地传输一个小文件到服务器\n",
        "5. 在服务器上确认文件已传输"]),

    md(["## 5. tmux——让程序在后台运行\n",
        "\n",
        "### 为什么需要tmux？\n",
        "\n",
        "当你通过SSH连接服务器运行训练时，如果网络断开或关闭终端，训练就会中断。\n",
        "tmux可以创建一个\"虚拟终端\"，即使你断开SSH，程序仍然在运行。\n",
        "\n",
        "### 核心操作\n",
        "\n",
        "| 操作 | 命令/按键 |\n",
        "|------|----------|\n",
        "| 新建session | `tmux new -s train` |\n",
        "| 分离session | `Ctrl+b` 然后按 `d` |\n",
        "| 重新连接 | `tmux attach -s train` |\n",
        "| 列出所有session | `tmux ls` |\n",
        "| 杀掉session | `tmux kill-session -t train` |\n",
        "| 在session中新建窗口 | `Ctrl+b` 然后按 `c` |\n",
        "| 切换窗口 | `Ctrl+b` 然后按 `0/1/2...` |\n"]),

    md(["### 典型工作流\n",
        "\n",
        "```bash\n",
        "# 1. SSH连接服务器\n",
        "ssh gpu-server\n",
        "\n",
        "# 2. 创建tmux session\n",
        "tmux new -s training\n",
        "\n",
        "# 3. 在tmux中运行训练\n",
        "python train.py --epochs 100\n",
        "\n",
        "# 4. 分离session（训练继续运行）\n",
        "# 按 Ctrl+b，然后按 d\n",
        "\n",
        "# 5. 断开SSH\n",
        "exit\n",
        "\n",
        "# --- 几小时后 ---\n",
        "\n",
        "# 6. 重新SSH连接\n",
        "ssh gpu-server\n",
        "\n",
        "# 7. 重新连接tmux session\n",
        "tmux attach -s training\n",
        "\n",
        "# 8. 查看训练进度\n",
        "```"]),

    md(["### 练习4：tmux\n",
        "\n",
        "1. 创建一个名为 `test` 的tmux session\n",
        "2. 在session中运行 `ping localhost`（模拟一个长时间运行的程序）\n",
        "3. 分离session（Ctrl+b 然后 d）\n",
        "4. 用 `tmux ls` 确认session还在运行\n",
        "5. 重新连接session\n",
        "6. 按 Ctrl+C 停止 ping\n",
        "7. 退出tmux"]),

    md(["## 6. Vim基础与VS Code Remote\n",
        "\n",
        "### 6.1 Vim最小生存指南\n",
        "\n",
        "Vim是Linux服务器上最常见的文本编辑器。你不需要精通Vim，只需要能改配置文件就行。\n",
        "\n",
        "```bash\n",
        "vim file.txt      # 打开文件\n",
        "```\n",
        "\n",
        "| 操作 | 按键 |\n",
        "|------|------|\n",
        "| 进入插入模式 | `i` |\n",
        "| 退出插入模式 | `Esc` |\n",
        "| 保存 | `:w` |\n",
        "| 退出 | `:q` |\n",
        "| 保存并退出 | `:wq` 或 `ZZ` |\n",
        "| 不保存退出 | `:q!` |\n",
        "| 搜索 | `/关键词` 然后 `n` 下一个 |\n",
        "\n",
        "**如果你不会Vim，可以用nano替代**：\n",
        "```bash\n",
        "nano file.txt     # 更简单的编辑器\n",
        "```\n"]),

    md(["### 6.2 VS Code Remote（推荐）\n",
        "\n",
        "VS Code Remote比Vim好用得多，强烈推荐。\n",
        "\n",
        "**设置步骤：**\n",
        "\n",
        "1. 在本地安装VS Code\n",
        "2. 安装 `Remote - SSH` 扩展\n",
        "3. 按 `Ctrl+Shift+P`，输入 `Remote-SSH: Connect to Host`\n",
        "4. 输入 `username@server_ip`\n",
        "5. 等待连接（首次需要安装VS Code Server）\n",
        "6. 连接成功后，就像在本地编辑一样\n",
        "\n",
        "**优点**：\n",
        "- 图形界面，不需要记Vim命令\n",
        "- 代码高亮、自动补全\n",
        "- 内置终端\n",
        "- Jupyter Notebook支持"]),

    md(["### 练习5：编辑文件\n",
        "\n",
        "1. 用Vim（或nano）在服务器上创建一个文件 `hello.py`，写入以下内容：\n",
        "   ```python\n",
        "   print('Hello from the server!')\n",
        "   ```\n",
        "2. 运行 `python hello.py` 确认输出\n",
        "3. 用VS Code Remote连接服务器，打开同一个文件并修改\n",
        "4. 再次运行确认修改生效"]),

    md(["## 7. 音频文件操作实战\n",
        "\n",
        "在CI/助听器研究中，我们经常需要批量处理音频文件。以下是一些常用操作。\n"]),

    md(["### 7.1 查看音频文件信息\n",
        "\n",
        "```bash\n",
        "# 使用soxi（sox的一部分）\n",
        "soxi file.wav\n",
        "\n",
        "# 使用ffprobe\n",
        "ffprobe file.wav\n",
        "```"]),

    md(["### 7.2 批量处理音频文件\n",
        "\n",
        "```bash\n",
        "# 批量转换采样率到16kHz\n",
        "mkdir -p resampled\n",
        "for f in *.wav; do\n",
        "    sox \"$f\" -r 16000 \"resampled/$f\"\n",
        "done\n",
        "\n",
        "# 批量转换格式（mp3 → wav）\n",
        "for f in *.mp3; do\n",
        "    ffmpeg -i \"$f\" \"${f%.mp3}.wav\"\n",
        "done\n",
        "\n",
        "# 统计wav文件数量\n",
        "find . -name '*.wav' | wc -l\n",
        "\n",
        "# 查看所有wav文件的总大小\n",
        "du -sh *.wav\n",
        "```"]),

    md(["### 练习6：音频文件操作\n",
        "\n",
        "**小挑战**：连接服务器后完成以下任务\n",
        "\n",
        "1. 在服务器上找到培训者指定的wav文件目录\n",
        "2. 统计wav文件的数量\n",
        "3. 查看其中一个wav文件的信息（采样率、时长、通道数）\n",
        "4. 计算整个目录下wav文件的总大小\n",
        "5. 用Python读取一个wav文件并打印其波形长度\n"]),

    code(["# 练习6的Python部分：读取wav文件\n",
          "import soundfile as sf\n",
          "import numpy as np\n",
          "\n",
          "# TODO: 替换为实际的文件路径\n",
          "# filepath = '/path/to/your/audio.wav'\n",
          "# waveform, sr = sf.read(filepath)\n",
          "# print(f'采样率: {sr} Hz')\n",
          "# print(f'波形长度: {len(waveform)} 个样本')\n",
          "# print(f'时长: {len(waveform)/sr:.2f} 秒')\n",
          "# print(f'通道数: {1 if waveform.ndim == 1 else waveform.shape[1]}')\n",
          "\n",
          "# 临时演示：生成一个模拟wav文件的元信息\n",
          "print('wav文件信息示例：')\n",
          "print(f'  采样率: 16000 Hz')\n",
          "print(f'  波形长度: 48000 个样本')\n",
          "print(f'  时长: 3.00 秒')\n",
          "print(f'  通道数: 1 (单声道)')"]),

    md(["## 本节要点\n",
        "\n",
        "1. **文件操作**：`cd`, `ls`, `pwd`, `mkdir`, `rm`, `cp`, `mv` 是最基本的命令\n",
        "2. **管道**：`|` 把命令串起来，是Linux最强大的特性之一\n",
        "3. **SSH**：远程连接服务器的标准方式，学会配置 `~/.ssh/config` 省很多时间\n",
        "4. **tmux**：让程序在后台运行，断开SSH也不中断训练\n",
        "5. **Vim**：只需要会打开、编辑、保存、退出；日常开发用VS Code Remote\n",
        "6. **音频操作**：`sox` 和 `ffmpeg` 是音频文件处理的瑞士军刀\n",
        "\n",
        "详细命令参考：[Linux速查表](../cheatsheet-linux.md) | [Vim速查表](../cheatsheet-vim.md)\n"]),

    md(["---\n",
        "下一节：[02-environment-setup.ipynb](02-environment-setup.ipynb) — 深度学习环境搭建"]),
]


# ============================================================
# Notebook 2: 深度学习环境搭建
# ============================================================
nb2_cells = [
    md(["# 深度学习环境搭建\n",
        "\n",
        "## 学习目标\n",
        "\n",
        "- 理解Conda环境管理的作用\n",
        "- 能创建、激活、管理Conda环境\n",
        "- 成功安装PyTorch并验证GPU可用\n",
        "- 能使用Jupyter Lab进行交互式开发\n",
        "- 了解Docker的基本概念和使用方式\n",
        "\n",
        "## 本节说明\n",
        "\n",
        "环境搭建是深度学习中最令人头疼的环节之一。本节课的目标是让每个人都能成功运行以下代码：\n",
        "\n",
        "```python\n",
        "import torch\n",
        "print(torch.cuda.is_available())  # True\n",
        "```\n"]),

    md(["## 1. Conda环境管理\n",
        "\n",
        "### 1.1 为什么需要虚拟环境？\n",
        "\n",
        "想象一下：\n",
        "- 项目A需要numpy 1.21，项目B需要numpy 1.24\n",
        "- 项目A需要Python 3.9，项目B需要Python 3.11\n",
        "\n",
        "如果没有虚拟环境，这些冲突会让你抓狂。虚拟环境就是给每个项目一个独立的\"工具箱\"。\n",
        "\n",
        "**类比**：虚拟环境就像实验室里的不同实验台，每个实验台有独立的仪器和试剂，互不干扰。\n"]),

    md(["### 1.2 Conda基本操作\n",
        "\n",
        "```bash\n",
        "# 创建环境\n",
        "conda create -n lab-training python=3.10\n",
        "\n",
        "# 激活环境\n",
        "conda activate lab-training\n",
        "\n",
        "# 退出环境\n",
        "conda deactivate\n",
        "\n",
        "# 列出所有环境\n",
        "conda env list\n",
        "\n",
        "# 删除环境\n",
        "conda env remove -n lab-training\n",
        "\n",
        "# 从配置文件创建环境\n",
        "conda env create -f environment.yml\n",
        "\n",
        "# 导出当前环境\n",
        "conda env export > environment.yml\n",
        "```\n"]),

    md(["### 1.3 安装包\n",
        "\n",
        "```bash\n",
        "# 安装单个包\n",
        "conda install numpy\n",
        "\n",
        "# 安装多个包\n",
        "conda install numpy scipy matplotlib\n",
        "\n",
        "# 用pip安装（conda找不到的包）\n",
        "pip install pesq pystoi\n",
        "\n",
        "# 查看已安装的包\n",
        "conda list\n",
        "\n",
        "# 更新包\n",
        "conda update numpy\n",
        "```\n",
        "\n",
        "**重要规则**：\n",
        "- 优先用 `conda install`，因为conda会处理二进制依赖\n",
        "- 如果conda找不到，再用 `pip install`\n",
        "- 不要在同一个环境中混用conda和pip安装同一个包\n"]),

    md(["### 练习1：创建Conda环境\n",
        "\n",
        "在终端中完成：\n",
        "\n",
        "1. 创建名为 `lab-training` 的环境，Python版本3.10：\n",
        "   ```bash\n",
        "   conda create -n lab-training python=3.10\n",
        "   ```\n",
        "2. 激活环境：\n",
        "   ```bash\n",
        "   conda activate lab-training\n",
        "   ```\n",
        "3. 确认Python版本：\n",
        "   ```bash\n",
        "   python --version\n",
        "   ```\n",
        "4. 确认你在正确的环境中：\n",
        "   ```bash\n",
        "   which python\n",
        "   ```\n",
        "   输出应该包含 `lab-training` 的路径"]),

    md(["## 2. PyTorch安装与验证\n",
        "\n",
        "### 2.1 安装PyTorch\n",
        "\n",
        "安装PyTorch最安全的方式是从[官网](https://pytorch.org/get-started/locally/)获取安装命令。\n",
        "\n",
        "根据你的系统和CUDA版本选择对应的命令。以下是常见的安装命令：\n",
        "\n",
        "```bash\n",
        "# CUDA 11.8（最常用）\n",
        "conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia\n",
        "\n",
        "# CUDA 12.1\n",
        "conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia\n",
        "\n",
        "# CPU版本（没有GPU时使用）\n",
        "conda install pytorch torchvision torchaudio cpuonly -c pytorch\n",
        "```\n",
        "\n",
        "**⚠️ 注意**：安装前确认服务器的CUDA版本！运行 `nvidia-smi` 查看右上角的CUDA版本。"]),

    md(["### 2.2 验证安装\n",
        "\n",
        "安装完成后，运行以下代码验证。这是本节课最重要的验证环节。\n"]),

    code(["# ====== 环境验证 ======\n",
          "# 如果所有输出都正常，说明环境配置成功！\n",
          "\n",
          "import sys\n",
          "print(f'Python版本: {sys.version}')\n",
          "print(f'Python路径: {sys.executable}')\n",
          "print()"]),

    code(["import torch\n",
          "print(f'PyTorch版本: {torch.__version__}')\n",
          "print(f'CUDA可用: {torch.cuda.is_available()}')\n",
          "if torch.cuda.is_available():\n",
          "    print(f'CUDA版本: {torch.version.cuda}')\n",
          "    print(f'GPU数量: {torch.cuda.device_count()}')\n",
          "    print(f'GPU名称: {torch.cuda.get_device_name(0)}')\n",
          "    print(f'GPU内存: {torch.cuda.get_device_properties(0).total_mem / 1024**3:.1f} GB')\n",
          "else:\n",
          "    print('⚠️ CUDA不可用！请检查安装。')\n",
          "print()"]),

    code(["import torchaudio\n",
          "print(f'torchaudio版本: {torchaudio.__version__}')\n",
          "print()"]),

    code(["import numpy as np\n",
          "import matplotlib\n",
          "import scipy\n",
          "import librosa\n",
          "\n",
          "print(f'NumPy版本: {np.__version__}')\n",
          "print(f'Matplotlib版本: {matplotlib.__version__}')\n",
          "print(f'SciPy版本: {scipy.__version__}')\n",
          "print(f'librosa版本: {librosa.__version__}')\n",
          "print()\n",
          "print('✅ 所有库导入成功！')"]),

    md(["### 2.3 GPU快速测试\n",
        "\n",
        "验证GPU确实可以用于计算："]),

    code(["# GPU快速测试\n",
          "if torch.cuda.is_available():\n",
          "    # 在GPU上创建张量并做计算\n",
          "    x = torch.randn(1000, 1000, device='cuda')\n",
          "    y = torch.randn(1000, 1000, device='cuda')\n",
          "    \n",
          "    # 矩阵乘法\n",
          "    import time\n",
          "    start = time.time()\n",
          "    z = torch.mm(x, y)\n",
          "    torch.cuda.synchronize()  # 等待GPU计算完成\n",
          "    elapsed = time.time() - start\n",
          "    \n",
          "    print(f'GPU矩阵乘法: 1000x1000, 耗时 {elapsed*1000:.2f} ms')\n",
          "    print(f'结果张量形状: {z.shape}')\n",
          "    print(f'结果张量设备: {z.device}')\n",
          "    print('✅ GPU计算正常！')\n",
          "else:\n",
          "    print('⚠️ GPU不可用，使用CPU进行计算')\n",
          "    x = torch.randn(1000, 1000)\n",
          "    y = torch.randn(1000, 1000)\n",
          "    z = torch.mm(x, y)\n",
          "    print(f'CPU矩阵乘法结果形状: {z.shape}')"]),

    md(["### 练习2：完成环境验证\n",
        "\n",
        "确保以上所有验证cell的输出都是正常的。特别注意：\n",
        "- `torch.cuda.is_available()` 返回 `True`\n",
        "- `torchaudio` 可以正常导入\n",
        "- `librosa` 可以正常导入\n",
        "\n",
        "如果任何一步失败，请参考\"环境问题排查清单\"。\n"]),

    md(["## 3. pip vs conda、requirements.txt\n",
        "\n",
        "### 3.1 pip vs conda\n",
        "\n",
        "| 特性 | conda | pip |\n",
        "|------|-------|-----|\n",
        "| 包来源 | Anaconda仓库 | PyPI |\n",
        "| 二进制依赖 | 自动处理 | 不处理 |\n",
        "| 非Python包 | 可以安装 | 不可以 |\n",
        "| 速度 | 较慢 | 较快 |\n",
        "| 包数量 | 较少 | 非常多 |\n",
        "\n",
        "**规则**：优先用conda，conda找不到再用pip。\n"]),

    md(["### 3.2 requirements.txt 和 environment.yml\n",
        "\n",
        "**requirements.txt**（pip格式）：\n",
        "```\n",
        "numpy>=1.21\n",
        "scipy>=1.7\n",
        "matplotlib>=3.4\n",
        "torch>=2.0\n",
        "librosa>=0.9\n",
        "```\n",
        "\n",
        "**environment.yml**（conda格式）：\n",
        "```yaml\n",
        "name: lab-training\n",
        "channels:\n",
        "  - pytorch\n",
        "  - conda-forge\n",
        "  - defaults\n",
        "dependencies:\n",
        "  - python=3.10\n",
        "  - numpy\n",
        "  - scipy\n",
        "  - matplotlib\n",
        "  - pytorch>=2.0\n",
        "  - torchaudio>=2.0\n",
        "  - librosa\n",
        "  - pip\n",
        "  - pip:\n",
        "    - pesq\n",
        "    - pystoi\n",
        "```\n",
        "\n",
        "**environment.yml 更适合分享**——它包含了完整的环境定义，别人可以一键复现。\n"]),

    md(["## 4. Docker基础\n",
        "\n",
        "### 4.1 Docker是什么？\n",
        "\n",
        "Docker是一种容器化技术，可以把整个环境（操作系统+依赖+代码）打包成一个\"镜像\"。\n",
        "\n",
        "**类比**：\n",
        "- Conda环境 = 在自己的房间里布置家具\n",
        "- Docker镜像 = 把整个房间打包，搬到任何地方都能用\n",
        "\n",
        "### 4.2 为什么用Docker？\n",
        "\n",
        "- **环境一致性**：\"在我机器上能跑\"的问题不存在了\n",
        "- **快速部署**：一条命令启动完整环境\n",
        "- **隔离性**：不同项目互不干扰\n"]),

    md(["### 4.3 Docker基本使用\n",
        "\n",
        "```bash\n",
        "# 拉取镜像\n",
        "docker pull pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime\n",
        "\n",
        "# 运行容器（带GPU支持）\n",
        "docker run --gpus all -p 8888:8888 -v $(pwd):/workspace lab-training\n",
        "\n",
        "# 参数说明：\n",
        "# --gpus all     使用所有GPU\n",
        "# -p 8888:8888   端口映射（Jupyter）\n",
        "# -v $(pwd):/workspace  挂载当前目录到容器的/workspace\n",
        "```\n",
        "\n",
        "**你不需要会写Dockerfile**——培训者已经准备好了预配置的镜像，你只需要会用就行。\n"]),

    md(["## 5. Jupyter Lab\n",
        "\n",
        "### 5.1 启动Jupyter Lab\n",
        "\n",
        "```bash\n",
        "# 在服务器上启动\n",
        "jupyter lab --no-browser --port=8888 --ip=0.0.0.0\n",
        "\n",
        "# 参数说明：\n",
        "# --no-browser    不自动打开浏览器\n",
        "# --port=8888     指定端口\n",
        "# --ip=0.0.0.0    允许远程访问\n",
        "```\n",
        "\n",
        "启动后，终端会显示一个URL，类似：\n",
        "```\n",
        "http://127.0.0.1:8888/lab?token=xxxxx\n",
        "```\n",
        "\n",
        "在本地浏览器中打开这个URL即可。\n"]),

    md(["### 5.2 SSH端口转发（如果直接访问不了）\n",
        "\n",
        "如果服务器的Jupyter端口不能直接访问，需要通过SSH端口转发：\n",
        "\n",
        "```bash\n",
        "# 在本地终端运行\n",
        "ssh -L 8888:localhost:8888 username@server_ip\n",
        "```\n",
        "\n",
        "然后在本地浏览器打开 `http://localhost:8888/lab?token=xxxxx`。\n"]),

    md(["### 5.3 Jupyter Lab快捷键\n",
        "\n",
        "| 快捷键 | 功能 |\n",
        "|--------|------|\n",
        "| `Shift+Enter` | 运行当前cell，跳到下一个 |\n",
        "| `Ctrl+Enter` | 运行当前cell，不跳转 |\n",
        "| `A` | 在当前cell上方插入新cell |\n",
        "| `B` | 在当前cell下方插入新cell |\n",
        "| `DD` | 删除当前cell |\n",
        "| `M` | 将cell切换为Markdown |\n",
        "| `Y` | 将cell切换为Code |\n",
        "| `Tab` | 自动补全 |\n",
        "| `Shift+Tab` | 查看函数文档 |"]),

    md(["## 6. 环境问题排查清单\n",
        "\n",
        "### 常见问题与解决方案\n",
        "\n",
        "| 问题 | 可能原因 | 解决方案 |\n",
        "|------|---------|----------|\n",
        "| `conda: command not found` | Conda未安装或未加入PATH | 安装Anaconda/Miniconda，重启终端 |\n",
        "| `torch.cuda.is_available() = False` | CUDA版本不匹配 | 运行 `nvidia-smi` 检查CUDA版本，重新安装对应版本 |\n",
        "| `ImportError: No module named 'xxx'` | 包未安装 | `conda install xxx` 或 `pip install xxx` |\n",
        "| `OSError: libcublas.so.11` | CUDA库缺失 | 安装对应的CUDA toolkit |\n",
        "| Jupyter打不开 | 端口未转发 | 检查SSH端口转发配置 |\n",
        "| `permission denied` | 权限不足 | 检查文件权限，`chmod +x` 或用sudo |\n",
        "| conda安装太慢 | 默认源在国外 | 配置国内镜像源 |\n"]),

    code(["# ====== 一键环境检测脚本 ======\n",
          "# 运行此cell，如果全部显示✅，说明环境配置成功\n",
          "\n",
          "import sys\n",
          "print('='*50)\n",
          "print('环境检测')\n",
          "print('='*50)\n",
          "\n",
          "# Python版本\n",
          "print(f'\\nPython: {sys.version.split()[0]}', '✅' if sys.version_info >= (3, 10) else '⚠️ 建议升级到3.10+')\n",
          "\n",
          "# 核心库\n",
          "libs = {\n",
          "    'numpy': 'np',\n",
          "    'torch': 'torch',\n",
          "    'torchaudio': 'torchaudio',\n",
          "    'matplotlib': 'matplotlib',\n",
          "    'scipy': 'scipy',\n",
          "    'librosa': 'librosa',\n",
          "    'soundfile': 'sf',\n",
          "}\n",
          "\n",
          "for lib_name, import_as in libs.items():\n",
          "    try:\n",
          "        mod = __import__(lib_name)\n",
          "        ver = getattr(mod, '__version__', 'unknown')\n",
          "        print(f'{lib_name}: {ver} ✅')\n",
          "    except ImportError:\n",
          "        print(f'{lib_name}: 未安装 ❌')\n",
          "\n",
          "# GPU\n",
          "import torch\n",
          "if torch.cuda.is_available():\n",
          "    print(f'\\nGPU: {torch.cuda.get_device_name(0)} ✅')\n",
          "    print(f'CUDA: {torch.version.cuda} ✅')\n",
          "    print(f'GPU内存: {torch.cuda.get_device_properties(0).total_mem / 1024**3:.1f} GB ✅')\n",
          "else:\n",
          "    print('\\nGPU: 不可用 ⚠️ (将使用CPU，训练会较慢)')\n",
          "\n",
          "print('\\n' + '='*50)\n",
          "print('如果所有项都显示✅，环境配置成功！')\n",
          "print('='*50)"]),

    md(["## 本节要点\n",
        "\n",
        "1. **Conda环境** = 独立的工具箱，一个项目一个环境，互不干扰\n",
        "2. **安装PyTorch**时一定要匹配CUDA版本，用 `nvidia-smi` 先确认\n",
        "3. **优先conda安装，pip补充**——conda处理二进制依赖更好\n",
        "4. **Docker**是环境的终极兜底方案——一条命令启动完整环境\n",
        "5. **Jupyter Lab**是交互式开发的核心工具——学会SSH端口转发\n",
        "6. 环境问题不可怕——大部分是版本不匹配，参考排查清单逐项检查\n"]),

    md(["---\n",
        "返回目录：[README.md](../README.md)"]),
]

write_notebook("01-linux-survival.ipynb", nb1_cells)
write_notebook("02-environment-setup.ipynb", nb2_cells)

print("\n模块1全部notebook生成完成！")
